In [1]:
import pandas as pd
from pandas_datareader import data

In [5]:
companies = ["MSFT", "GOOG", "AAPL", "YHOO", "AMZN"]
p = data.DataReader(name=companies, data_source="yahoo", start="2010-01-01", end="2016-12-31")
p

Attributes        High                                                 Low  \
Symbols           AAPL        AMZN        GOOG       MSFT YHOO        AAPL
Date
2010-01-04   30.642857  136.610001  312.721039  31.100000  NaN   30.340000
2010-01-05   30.798571  135.479996  311.891449  31.100000  NaN   30.464285
2010-01-06   30.747143  134.729996  310.907837  31.080000  NaN   30.107143
2010-01-07   30.285715  132.320007  303.029083  30.700001  NaN   29.864286
2010-01-08   30.285715  133.679993  299.675903  30.879999  NaN   29.865715
2010-01-11   30.428572  132.800003  300.276978  30.760000  NaN   29.778572
2010-01-12   29.967142  129.820007  297.147339  30.400000  NaN   29.488571
2010-01-13   30.132856  129.710007  292.288940  30.520000  NaN   29.157143
2010-01-14   30.065714  130.380005  295.180145  31.100000  NaN   29.860001
2010-01-15   30.228571  129.649994  294.862213  31.240000  NaN   29.410000
2010-01-19   30.741428  128.000000  293.302338  31.240000  NaN   29.605715
2010-01-20   30.792856  129.199997  291.096710  30.940001  NaN   29.928572
2010-01-21   30.472857  128.149994  291.513977  30.719999  NaN   29.601429
2010-01-22   29.642857  127.669998  283.456390  30.200001  NaN   28.165714
2010-01-25   29.242857  122.279999  273.163330  29.660000  NaN   28.598572
2010-01-26   30.530001  122.980003  273.024231  29.850000  NaN   28.940001
2010-01-27   30.082857  123.330002  272.055542  29.820000  NaN   28.504286
2010-01-28   29.357143  127.199997  271.732635  29.870001  NaN   28.385714
2010-01-29   28.885714  131.850006  268.747070  29.920000  NaN   27.178572
2010-02-01   28.000000  124.860001  266.173798  28.480000  NaN   27.328571
2010-02-02   28.045713  118.980003  265.751556  28.500000  NaN   27.625713
2010-02-03   28.600000  119.610001  269.298462  28.790001  NaN   27.774286
2010-02-04   28.338572  120.330002  267.261719  28.500000  NaN   27.367144
2010-02-05   28.000000  117.650002  265.026245  28.280001  NaN   27.264286
2010-02-08   28.268572  121.000000  269.248810  28.080000  NaN   27.714285
2010-02-09   28.214285  119.089996  269.015320  28.340000  NaN   27.821428
2010-02-10   28.085714  118.610001  267.157410  28.240000  NaN   27.751429
2010-02-11   28.535715  120.419998  268.498688  28.400000  NaN   27.722857
2010-02-12   28.805714  119.940002  266.839478  28.059999  NaN   27.928572
2010-02-16   29.098572  120.500000  270.306915  28.370001  NaN   28.788572
...                ...         ...         ...        ...  ...         ...
2016-11-17  110.349998  757.500000  772.700012  60.950001  NaN  108.830002
2016-11-18  110.540001  767.739990  775.000000  61.139999  NaN  109.660004
2016-11-21  111.989998  780.349976  769.700012  60.970001  NaN  110.010002
2016-11-22  112.419998  792.400024  776.960022  61.259998  NaN  111.400002
2016-11-23  111.510002  781.750000  768.283020  61.099998  NaN  110.330002
2016-11-25  111.870003  786.750000  765.000000  60.529999  NaN  110.949997
2016-11-28  112.470001  777.000000  779.530029  61.020000  NaN  111.389999
2016-11-29  112.029999  769.890015  778.500000  61.410000  NaN  110.070000
2016-11-30  112.199997  768.090027  772.989990  61.180000  NaN  110.269997
2016-12-01  110.940002  753.369995  759.849976  60.150002  NaN  109.029999
2016-12-02  110.089996  748.489990  754.000000  59.470001  NaN  108.849998
2016-12-05  110.029999  761.489990  763.900024  60.590000  NaN  108.250000
2016-12-06  110.360001  768.239990  768.830017  60.459999  NaN  109.190002
2016-12-07  111.190002  770.419983  771.359985  61.380001  NaN  109.160004
2016-12-08  112.430000  773.789978  778.179993  61.580002  NaN  110.599998
2016-12-09  114.699997  770.250000  789.429993  61.990002  NaN  112.309998
2016-12-12  115.000000  766.890015  791.250000  62.299999  NaN  112.489998
2016-12-13  115.919998  782.460022  804.380005  63.419998  NaN  113.750000
2016-12-14  116.199997  780.859985  804.000000  63.450001  NaN  114.980003
2016-12-15  116.730003  769.099976  803.000000  63.150002  NaN  115.230003
2016-12-16  116.500000  765.130005  800.856018  62.950001  NaN  115.650002
2016-12-19  117.379997  770.500000  797.659973  63.770000  NaN  115.750000
2016-12-20  117.500000  774.390015  798.650024  63.799999  NaN  116.680000
2016-12-21  117.400002  771.219971  796.676025  63.700001  NaN  116.779999
2016-12-22  116.510002  771.210022  793.320007  64.099998  NaN  115.639999
2016-12-23  116.519997  766.500000  792.739990  63.540001  NaN  115.589996
2016-12-27  117.800003  774.650024  797.859985  64.070000  NaN  116.489998
2016-12-28  118.019997  780.000000  794.229980  63.400002  NaN  116.199997
2016-12-29  117.110001  773.400024  785.929993  63.200001  NaN  116.400002
2016-12-30  117.199997  767.400024  782.780029  62.990002  NaN  115.430000

Attributes                                         ...        Volume  \
Symbols           AMZN        GOOG       MSFT YHOO ...          AAPL
Date                                               ...
2010-01-04  133.139999  310.103088  30.590000  NaN ...   123432400.0
2010-01-05  131.809998  308.761810  30.639999  NaN ...   150476200.0
2010-01-06  131.649994  301.220856  30.520000  NaN ...   138040000.0
2010-01-07  128.800003  294.410156  30.190001  NaN ...   119282800.0
2010-01-08  129.029999  292.651581  30.240000  NaN ...   111902700.0
2010-01-11  129.210007  295.100647  30.120001  NaN ...   115557400.0
2010-01-12  126.550003  292.100159  29.910000  NaN ...   148614900.0
2010-01-13  125.750000  285.095734  30.010000  NaN ...   151473000.0
2010-01-14  126.400002  289.521942  30.260000  NaN ...   108223500.0
2010-01-15  127.059998  287.152344  30.709999  NaN ...   148516900.0
2010-01-19  124.330002  286.283020  30.680000  NaN ...   182501900.0
2010-01-20  125.080002  285.786224  30.309999  NaN ...   153038200.0
2010-01-21  125.000000  284.276062  30.000000  NaN ...   152038600.0
2010-01-22  120.760002  265.701874  28.840000  NaN ...   220441900.0
2010-01-25  118.120003  266.024780  29.100000  NaN ...   266424900.0
2010-01-26  119.059998  266.412231  29.090000  NaN ...   466777500.0
2010-01-27  118.800003  265.925415  29.020000  NaN ...   430642100.0
2010-01-28  122.800003  263.585632  28.889999  NaN ...   293375600.0
2010-01-29  124.139999  261.106750  27.660000  NaN ...   311488100.0
2010-02-01  113.820000  263.436584  27.920000  NaN ...   187469100.0
2010-02-02  114.400002  262.100281  28.139999  NaN ...   174585600.0
2010-02-03  116.559998  262.408295  28.120001  NaN ...   153832000.0
2010-02-04  115.739998  261.081909  27.809999  NaN ...   189413000.0
2010-02-05  114.099998  259.541931  27.570000  NaN ...   212576700.0
2010-02-08  116.559998  264.047638  27.570000  NaN ...   119567700.0
2010-02-09  117.000000  265.806183  27.750000  NaN ...   158221700.0
2010-02-10  116.000000  262.140045  27.840000  NaN ...    92590400.0
2010-02-11  116.500000  263.039185  27.700001  NaN ...   137586400.0
2010-02-12  117.500000  263.535950  27.580000  NaN ...   163867200.0
2010-02-16  117.180000  265.423676  28.020000  NaN ...   135934400.0
...                ...         ...        ...  ... ...           ...
2016-11-17  748.000000  764.229980  59.970001  NaN ...    27632000.0
2016-11-18  757.640015  760.000000  60.299999  NaN ...    28428900.0
2016-11-21  765.109985  760.599976  60.419998  NaN ...    29264600.0
2016-11-22  781.000000  767.000000  60.810001  NaN ...    25965500.0
2016-11-23  773.119995  755.250000  60.250000  NaN ...    27426400.0
2016-11-25  777.900024  760.520020  60.130001  NaN ...    11475900.0
2016-11-28  764.239990  759.799988  60.209999  NaN ...    27194000.0
2016-11-29  761.320007  768.239990  60.520000  NaN ...    28528800.0
2016-11-30  750.250000  754.830017  60.220001  NaN ...    36162300.0
2016-12-01  738.030029  737.025024  58.939999  NaN ...    37086900.0
2016-12-02  736.700012  743.099976  58.799999  NaN ...    26528000.0
2016-12-05  742.000000  752.900024  59.560001  NaN ...    34324500.0
2016-12-06  757.250000  757.340027  59.799999  NaN ...    26195500.0
2016-12-07  755.820007  755.799988  59.799999  NaN ...    29998700.0
2016-12-08  765.190002  767.229980  60.840000  NaN ...    27068300.0
2016-12-09  765.340027  779.020996  61.130001  NaN ...    34402600.0
2016-12-12  757.200012  784.354980  61.720001  NaN ...    26374400.0
2016-12-13  762.000000  793.340027  62.240002  NaN ...    43733800.0
2016-12-14  762.809998  794.010010  62.529999  NaN ...    34031800.0
2016-12-15  760.309998  792.919983  62.299999  NaN ...    46524500.0
2016-12-16  754.000000  790.289978  62.119999  NaN ...    44351100.0
2016-12-19  756.159973  786.270020  62.419998  NaN ...    27779400.0
2016-12-20  767.710022  793.270020  63.029999  NaN ...    21425000.0
2016-12-21  765.700012  787.099976  63.119999  NaN ...    23783200.0
2016-12-22  763.020020  788.580017  63.410000  NaN ...    26085900.0
2016-12-23  757.989990  787.280029  62.799999  NaN ...    14249500.0
2016-12-27  761.200012  787.656982  63.209999  NaN ...    18296900.0
2016-12-28  770.500000  783.200012  62.830002  NaN ...    20905900.0
2016-12-29  760.849976  778.919983  62.730000  NaN ...    15039500.0
2016-12-30  748.280029  770.409973  62.029999  NaN ...    30586300.0

Attributes                                             Adj Close              \
Symbols           AMZN        GOOG         MSFT YHOO        AAPL        AMZN
Date
2010-01-04   7599900.0   3937800.0   38409100.0  NaN   20.473503  133.899994
2010-01-05   8851900.0   6048500.0   49749600.0  NaN   20.508902  134.690002
2010-01-06   7178800.0   8009000.0   58182400.0  NaN   20.182680  132.250000
2010-01-07  11030200.0  12912000.0   50559700.0  NaN   20.145369  130.000000
2010-01-08   9830500.0   9509900.0   51197400.0  NaN   20.279305  133.520004
2010-01-11   8779400.0  14519600.0   68754700.0  NaN   20.100410  130.309998
2010-01-12   9096300.0   9769600.0   65912100.0  NaN   19.871763  127.349998
2010-01-13  10723200.0  13077600.0   51863500.0  NaN   20.152065  129.110001
2010-01-14   9774900.0   8535300.0   63228100.0  NaN   20.035355  127.349998
2010-01-15  15376500.0  10939600.0   79913200.0  NaN   19.700523  127.139999
2010-01-19   8892600.0   8689500.0   46575700.0  NaN   20.572037  127.610001
2010-01-20   9074700.0   6543600.0   54849500.0  NaN   20.255390  125.779999
2010-01-21   9970600.0  12697400.0   73086700.0  NaN   19.905249  126.620003
2010-01-22  11568900.0  13689200.0  102004600.0  NaN   18.917973  121.430000
2010-01-25  12023900.0   8897200.0   63373000.0  NaN   19.426920  120.309998
2010-01-26   9559000.0   8767600.0   66639900.0  NaN   19.701479  119.480003
2010-01-27  14765300.0   7980200.0   63949500.0  NaN   19.887072  122.750000
2010-01-28  27293100.0   6500100.0  117513700.0  NaN   19.065300  126.029999
2010-01-29  29471300.0   8334700.0  193888500.0  NaN   18.373636  125.410004
2010-02-01  37774400.0   4530800.0   85931100.0  NaN   18.629066  118.870003
2010-02-02  23079700.0   8245600.0   54413700.0  NaN   18.737165  118.120003
2010-02-03  12405900.0   6037000.0   61397900.0  NaN   19.059557  119.099998
2010-02-04  12784000.0   6799200.0   77850000.0  NaN   18.372683  115.940002
2010-02-05  11024800.0   6353000.0   80960100.0  NaN   18.698900  117.389999
2010-02-08   9890200.0   5423500.0   52820600.0  NaN   18.570709  116.830002
2010-02-09   9223000.0   5675700.0   59195800.0  NaN   18.768732  118.029999
2010-02-10   6233200.0   5383700.0   48591300.0  NaN   18.666370  117.360001
2010-02-11   8343500.0   4851300.0   65993700.0  NaN   19.005989  120.089996
2010-02-12   8073500.0   4589000.0   81117200.0  NaN   19.169575  119.660004
2010-02-16   8932700.0   7356200.0   51935600.0  NaN   19.458488  117.529999
...                ...         ...          ...  ...         ...         ...
2016-11-17   3690100.0   1304000.0   32132700.0  NaN  106.609329  756.400024
2016-11-18   4373400.0   1547100.0   27686300.0  NaN  106.715996  760.159973
2016-11-21   4614600.0   1330600.0   19652600.0  NaN  108.335266  780.000000
2016-11-22   5311300.0   1593100.0   23206700.0  NaN  108.403137  785.330017
2016-11-23   3522500.0   1477400.0   21847200.0  NaN  107.850449  780.119995
2016-11-25   1837100.0    587400.0    8409600.0  NaN  108.393433  780.369995
2016-11-28   4438800.0   2188200.0   20732600.0  NaN  108.180122  766.770020
2016-11-29   3272300.0   1616600.0   22366700.0  NaN  108.073463  762.520020
2016-11-30   4625900.0   2392900.0   34655400.0  NaN  107.162018  750.570007
2016-12-01   4666000.0   3017900.0   34542100.0  NaN  106.163315  743.650024
2016-12-02   3561300.0   1452500.0   25515700.0  NaN  106.560860  740.340027
2016-12-05   4314700.0   1394200.0   23552700.0  NaN  105.794868  759.359985
2016-12-06   3794700.0   1690700.0   19907000.0  NaN  106.609329  764.719971
2016-12-07   3684900.0   1761000.0   30809000.0  NaN  107.656517  770.419983
2016-12-08   3189600.0   1488100.0   21220800.0  NaN  108.713409  767.330017
2016-12-09   2470900.0   1821900.0   27349400.0  NaN  110.487801  768.659973
2016-12-12   2963900.0   2104100.0   20198100.0  NaN  109.857559  760.119995
2016-12-13   5285300.0   2145200.0   35718900.0  NaN  111.690132  774.340027
2016-12-14   5454800.0   1704200.0   30352700.0  NaN  111.690132  768.820007
2016-12-15   3801900.0   1626500.0   27669900.0  NaN  112.300980  761.000000
2016-12-16   4828700.0   2428300.0   42204700.0  NaN  112.446442  757.770020
2016-12-19   3113200.0   1232100.0   34338200.0  NaN  113.096069  766.000000
2016-12-20   2703600.0    951000.0   26028400.0  NaN  113.396652  771.219971
2016-12-21   2044600.0   1211300.0   17096300.0  NaN  113.503304  770.599976
2016-12-22   2543600.0    972200.0   22176600.0  NaN  112.756714  766.340027
2016-12-23   1976900.0    623400.0   12398000.0  NaN  112.979713  760.590027
2016-12-27   2638700.0    789100.0   11763200.0  NaN  113.697243  771.400024
2016-12-28   3301000.0   1153800.0   14653300.0  NaN  113.212425  772.130005
2016-12-29   3153500.0    742200.0   10181600.0  NaN  113.183334  765.150024
2016-12-30   4139400.0   1770000.0   25579900.0  NaN  112.300980  749.869995

Attributes
Symbols           GOOG       MSFT YHOO
Date
2010-01-04  311.349976  24.720928  NaN
2010-01-05  309.978882  24.728914  NaN
2010-01-06  302.164703  24.577150  NaN
2010-01-07  295.130463  24.321552  NaN
2010-01-08  299.064880  24.489288  NaN
2010-01-11  298.612823  24.177786  NaN
2010-01-12  293.332153  24.018032  NaN
2010-01-13  291.648102  24.241684  NaN
2010-01-14  293.019196  24.728914  NaN
2010-01-15  288.126007  24.649038  NaN
2010-01-19  291.911407  24.840738  NaN
2010-01-20  288.329681  24.433378  NaN
2010-01-21  289.606384  23.970112  NaN
2010-01-22  273.227905  23.131437  NaN
2010-01-25  268.255249  23.418983  NaN
2010-01-26  269.457428  23.562756  NaN
2010-01-27  269.298462  23.698549  NaN
2010-01-28  265.418701  23.291180  NaN
2010-01-29  263.257751  22.508421  NaN
2010-02-01  264.787811  22.692129  NaN
2010-02-02  263.843964  22.732069  NaN
2010-02-03  268.662598  22.867855  NaN
2010-02-04  261.687958  22.236853  NaN
2010-02-05  263.928406  22.380629  NaN
2010-02-08  265.011353  22.141001  NaN
2010-02-09  266.486755  22.372641  NaN
2010-02-10  265.498199  22.356657  NaN
2010-02-11  266.466888  22.460506  NaN
2010-02-12  264.837494  22.308741  NaN
2010-02-16  268.901062  22.750099  NaN
...                ...        ...  ...
2016-11-17  771.229980  58.306213  NaN
2016-11-18  760.539978  58.027370  NaN
2016-11-21  769.200012  58.517738  NaN
2016-11-22  768.270020  58.767731  NaN
2016-11-23  760.989990  58.075451  NaN
2016-11-25  761.679993  58.200436  NaN
2016-11-28  768.239990  58.277363  NaN
2016-11-29  770.840027  58.738884  NaN
2016-11-30  758.039978  57.940830  NaN
2016-12-01  747.919983  56.921623  NaN
2016-12-02  750.500000  56.969700  NaN
2016-12-05  762.520020  57.902378  NaN
2016-12-06  759.109985  57.642761  NaN
2016-12-07  771.190002  59.008118  NaN
2016-12-08  776.419983  58.661968  NaN
2016-12-09  789.289978  59.585018  NaN
2016-12-12  789.270020  59.777321  NaN
2016-12-13  796.099976  60.556149  NaN
2016-12-14  797.070007  60.267696  NaN
2016-12-15  797.849976  60.171543  NaN
2016-12-16  790.799988  59.902313  NaN
2016-12-19  794.200012  61.171520  NaN
2016-12-20  796.419983  61.094597  NaN
2016-12-21  794.559998  61.094597  NaN
2016-12-22  791.260010  61.104214  NaN
2016-12-23  789.909973  60.806145  NaN
2016-12-27  791.549988  60.844601  NaN
2016-12-28  785.049988  60.565762  NaN
2016-12-29  782.789978  60.479229  NaN
2016-12-30  771.820007  59.748470  NaN

[1762 rows x 30 columns]

# the axes of a Panel object

In [9]:
p.items

<bound method DataFrame.iteritems of Attributes        High                                                 Low  \
Symbols           AAPL        AMZN        GOOG       MSFT YHOO        AAPL
Date
2010-01-04   30.642857  136.610001  312.721039  31.100000  NaN   30.340000
2010-01-05   30.798571  135.479996  311.891449  31.100000  NaN   30.464285
2010-01-06   30.747143  134.729996  310.907837  31.080000  NaN   30.107143
2010-01-07   30.285715  132.320007  303.029083  30.700001  NaN   29.864286
2010-01-08   30.285715  133.679993  299.675903  30.879999  NaN   29.865715
2010-01-11   30.428572  132.800003  300.276978  30.760000  NaN   29.778572
2010-01-12   29.967142  129.820007  297.147339  30.400000  NaN   29.488571
2010-01-13   30.132856  129.710007  292.288940  30.520000  NaN   29.157143
2010-01-14   30.065714  130.380005  295.180145  31.100000  NaN   29.860001
2010-01-15   30.228571  129.649994  294.862213  31.240000  NaN   29.410000
2010-01-19   30.741428  128.000000  293.302338  31.240000  NaN   29.605715
2010-01-20   30.792856  129.199997  291.096710  30.940001  NaN   29.928572
2010-01-21   30.472857  128.149994  291.513977  30.719999  NaN   29.601429
2010-01-22   29.642857  127.669998  283.456390  30.200001  NaN   28.165714
2010-01-25   29.242857  122.279999  273.163330  29.660000  NaN   28.598572
2010-01-26   30.530001  122.980003  273.024231  29.850000  NaN   28.940001
2010-01-27   30.082857  123.330002  272.055542  29.820000  NaN   28.504286
2010-01-28   29.357143  127.199997  271.732635  29.870001  NaN   28.385714
2010-01-29   28.885714  131.850006  268.747070  29.920000  NaN   27.178572
2010-02-01   28.000000  124.860001  266.173798  28.480000  NaN   27.328571
2010-02-02   28.045713  118.980003  265.751556  28.500000  NaN   27.625713
2010-02-03   28.600000  119.610001  269.298462  28.790001  NaN   27.774286
2010-02-04   28.338572  120.330002  267.261719  28.500000  NaN   27.367144
2010-02-05   28.000000  117.650002  265.026245  28.280001  NaN   27.264286
2010-02-08   28.268572  121.000000  269.248810  28.080000  NaN   27.714285
2010-02-09   28.214285  119.089996  269.015320  28.340000  NaN   27.821428
2010-02-10   28.085714  118.610001  267.157410  28.240000  NaN   27.751429
2010-02-11   28.535715  120.419998  268.498688  28.400000  NaN   27.722857
2010-02-12   28.805714  119.940002  266.839478  28.059999  NaN   27.928572
2010-02-16   29.098572  120.500000  270.306915  28.370001  NaN   28.788572
...                ...         ...         ...        ...  ...         ...
2016-11-17  110.349998  757.500000  772.700012  60.950001  NaN  108.830002
2016-11-18  110.540001  767.739990  775.000000  61.139999  NaN  109.660004
2016-11-21  111.989998  780.349976  769.700012  60.970001  NaN  110.010002
2016-11-22  112.419998  792.400024  776.960022  61.259998  NaN  111.400002
2016-11-23  111.510002  781.750000  768.283020  61.099998  NaN  110.330002
2016-11-25  111.870003  786.750000  765.000000  60.529999  NaN  110.949997
2016-11-28  112.470001  777.000000  779.530029  61.020000  NaN  111.389999
2016-11-29  112.029999  769.890015  778.500000  61.410000  NaN  110.070000
2016-11-30  112.199997  768.090027  772.989990  61.180000  NaN  110.269997
2016-12-01  110.940002  753.369995  759.849976  60.150002  NaN  109.029999
2016-12-02  110.089996  748.489990  754.000000  59.470001  NaN  108.849998
2016-12-05  110.029999  761.489990  763.900024  60.590000  NaN  108.250000
2016-12-06  110.360001  768.239990  768.830017  60.459999  NaN  109.190002
2016-12-07  111.190002  770.419983  771.359985  61.380001  NaN  109.160004
2016-12-08  112.430000  773.789978  778.179993  61.580002  NaN  110.599998
2016-12-09  114.699997  770.250000  789.429993  61.990002  NaN  112.309998
2016-12-12  115.000000  766.890015  791.250000  62.299999  NaN  112.489998
2016-12-13  115.919998  782.460022  804.380005  63.419998  NaN  113.750000
2016-12-14  116.199997  780.859985  804.000000  63.450001  NaN  114.980003
2016-12-15  116.730003  769.099976  803.000000  63.150002  NaN  115.230003
2016-12-16  116.500000  765.130005  800.856018  62.950001  NaN  115.650002
2016-12-19  117.379997  770.500000  797.659973  63.770000  NaN  115.750000
2016-12-20  117.500000  774.390015  798.650024  63.799999  NaN  116.680000
2016-12-21  117.400002  771.219971  796.676025  63.700001  NaN  116.779999
2016-12-22  116.510002  771.210022  793.320007  64.099998  NaN  115.639999
2016-12-23  116.519997  766.500000  792.739990  63.540001  NaN  115.589996
2016-12-27  117.800003  774.650024  797.859985  64.070000  NaN  116.489998
2016-12-28  118.019997  780.000000  794.229980  63.400002  NaN  116.199997
2016-12-29  117.110001  773.400024  785.929993  63.200001  NaN  116.400002
2016-12-30  117.199997  767.400024  782.780029  62.990002  NaN  115.430000

Attributes                                         ...        Volume  \
Symbols           AMZN        GOOG       MSFT YHOO ...          AAPL
Date                                               ...
2010-01-04  133.139999  310.103088  30.590000  NaN ...   123432400.0
2010-01-05  131.809998  308.761810  30.639999  NaN ...   150476200.0
2010-01-06  131.649994  301.220856  30.520000  NaN ...   138040000.0
2010-01-07  128.800003  294.410156  30.190001  NaN ...   119282800.0
2010-01-08  129.029999  292.651581  30.240000  NaN ...   111902700.0
2010-01-11  129.210007  295.100647  30.120001  NaN ...   115557400.0
2010-01-12  126.550003  292.100159  29.910000  NaN ...   148614900.0
2010-01-13  125.750000  285.095734  30.010000  NaN ...   151473000.0
2010-01-14  126.400002  289.521942  30.260000  NaN ...   108223500.0
2010-01-15  127.059998  287.152344  30.709999  NaN ...   148516900.0
2010-01-19  124.330002  286.283020  30.680000  NaN ...   182501900.0
2010-01-20  125.080002  285.786224  30.309999  NaN ...   153038200.0
2010-01-21  125.000000  284.276062  30.000000  NaN ...   152038600.0
2010-01-22  120.760002  265.701874  28.840000  NaN ...   220441900.0
2010-01-25  118.120003  266.024780  29.100000  NaN ...   266424900.0
2010-01-26  119.059998  266.412231  29.090000  NaN ...   466777500.0
2010-01-27  118.800003  265.925415  29.020000  NaN ...   430642100.0
2010-01-28  122.800003  263.585632  28.889999  NaN ...   293375600.0
2010-01-29  124.139999  261.106750  27.660000  NaN ...   311488100.0
2010-02-01  113.820000  263.436584  27.920000  NaN ...   187469100.0
2010-02-02  114.400002  262.100281  28.139999  NaN ...   174585600.0
2010-02-03  116.559998  262.408295  28.120001  NaN ...   153832000.0
2010-02-04  115.739998  261.081909  27.809999  NaN ...   189413000.0
2010-02-05  114.099998  259.541931  27.570000  NaN ...   212576700.0
2010-02-08  116.559998  264.047638  27.570000  NaN ...   119567700.0
2010-02-09  117.000000  265.806183  27.750000  NaN ...   158221700.0
2010-02-10  116.000000  262.140045  27.840000  NaN ...    92590400.0
2010-02-11  116.500000  263.039185  27.700001  NaN ...   137586400.0
2010-02-12  117.500000  263.535950  27.580000  NaN ...   163867200.0
2010-02-16  117.180000  265.423676  28.020000  NaN ...   135934400.0
...                ...         ...        ...  ... ...           ...
2016-11-17  748.000000  764.229980  59.970001  NaN ...    27632000.0
2016-11-18  757.640015  760.000000  60.299999  NaN ...    28428900.0
2016-11-21  765.109985  760.599976  60.419998  NaN ...    29264600.0
2016-11-22  781.000000  767.000000  60.810001  NaN ...    25965500.0
2016-11-23  773.119995  755.250000  60.250000  NaN ...    27426400.0
2016-11-25  777.900024  760.520020  60.130001  NaN ...    11475900.0
2016-11-28  764.239990  759.799988  60.209999  NaN ...    27194000.0
2016-11-29  761.320007  768.239990  60.520000  NaN ...    28528800.0
2016-11-30  750.250000  754.830017  60.220001  NaN ...    36162300.0
2016-12-01  738.030029  737.025024  58.939999  NaN ...    37086900.0
2016-12-02  736.700012  743.099976  58.799999  NaN ...    26528000.0
2016-12-05  742.000000  752.900024  59.560001  NaN ...    34324500.0
2016-12-06  757.250000  757.340027  59.799999  NaN ...    26195500.0
2016-12-07  755.820007  755.799988  59.799999  NaN ...    29998700.0
2016-12-08  765.190002  767.229980  60.840000  NaN ...    27068300.0
2016-12-09  765.340027  779.020996  61.130001  NaN ...    34402600.0
2016-12-12  757.200012  784.354980  61.720001  NaN ...    26374400.0
2016-12-13  762.000000  793.340027  62.240002  NaN ...    43733800.0
2016-12-14  762.809998  794.010010  62.529999  NaN ...    34031800.0
2016-12-15  760.309998  792.919983  62.299999  NaN ...    46524500.0
2016-12-16  754.000000  790.289978  62.119999  NaN ...    44351100.0
2016-12-19  756.159973  786.270020  62.419998  NaN ...    27779400.0
2016-12-20  767.710022  793.270020  63.029999  NaN ...    21425000.0
2016-12-21  765.700012  787.099976  63.119999  NaN ...    23783200.0
2016-12-22  763.020020  788.580017  63.410000  NaN ...    26085900.0
2016-12-23  757.989990  787.280029  62.799999  NaN ...    14249500.0
2016-12-27  761.200012  787.656982  63.209999  NaN ...    18296900.0
2016-12-28  770.500000  783.200012  62.830002  NaN ...    20905900.0
2016-12-29  760.849976  778.919983  62.730000  NaN ...    15039500.0
2016-12-30  748.280029  770.409973  62.029999  NaN ...    30586300.0

Attributes                                             Adj Close              \
Symbols           AMZN        GOOG         MSFT YHOO        AAPL        AMZN
Date
2010-01-04   7599900.0   3937800.0   38409100.0  NaN   20.473503  133.899994
2010-01-05   8851900.0   6048500.0   49749600.0  NaN   20.508902  134.690002
2010-01-06   7178800.0   8009000.0   58182400.0  NaN   20.182680  132.250000
2010-01-07  11030200.0  12912000.0   50559700.0  NaN   20.145369  130.000000
2010-01-08   9830500.0   9509900.0   51197400.0  NaN   20.279305  133.520004
2010-01-11   8779400.0  14519600.0   68754700.0  NaN   20.100410  130.309998
2010-01-12   9096300.0   9769600.0   65912100.0  NaN   19.871763  127.349998
2010-01-13  10723200.0  13077600.0   51863500.0  NaN   20.152065  129.110001
2010-01-14   9774900.0   8535300.0   63228100.0  NaN   20.035355  127.349998
2010-01-15  15376500.0  10939600.0   79913200.0  NaN   19.700523  127.139999
2010-01-19   8892600.0   8689500.0   46575700.0  NaN   20.572037  127.610001
2010-01-20   9074700.0   6543600.0   54849500.0  NaN   20.255390  125.779999
2010-01-21   9970600.0  12697400.0   73086700.0  NaN   19.905249  126.620003
2010-01-22  11568900.0  13689200.0  102004600.0  NaN   18.917973  121.430000
2010-01-25  12023900.0   8897200.0   63373000.0  NaN   19.426920  120.309998
2010-01-26   9559000.0   8767600.0   66639900.0  NaN   19.701479  119.480003
2010-01-27  14765300.0   7980200.0   63949500.0  NaN   19.887072  122.750000
2010-01-28  27293100.0   6500100.0  117513700.0  NaN   19.065300  126.029999
2010-01-29  29471300.0   8334700.0  193888500.0  NaN   18.373636  125.410004
2010-02-01  37774400.0   4530800.0   85931100.0  NaN   18.629066  118.870003
2010-02-02  23079700.0   8245600.0   54413700.0  NaN   18.737165  118.120003
2010-02-03  12405900.0   6037000.0   61397900.0  NaN   19.059557  119.099998
2010-02-04  12784000.0   6799200.0   77850000.0  NaN   18.372683  115.940002
2010-02-05  11024800.0   6353000.0   80960100.0  NaN   18.698900  117.389999
2010-02-08   9890200.0   5423500.0   52820600.0  NaN   18.570709  116.830002
2010-02-09   9223000.0   5675700.0   59195800.0  NaN   18.768732  118.029999
2010-02-10   6233200.0   5383700.0   48591300.0  NaN   18.666370  117.360001
2010-02-11   8343500.0   4851300.0   65993700.0  NaN   19.005989  120.089996
2010-02-12   8073500.0   4589000.0   81117200.0  NaN   19.169575  119.660004
2010-02-16   8932700.0   7356200.0   51935600.0  NaN   19.458488  117.529999
...                ...         ...          ...  ...         ...         ...
2016-11-17   3690100.0   1304000.0   32132700.0  NaN  106.609329  756.400024
2016-11-18   4373400.0   1547100.0   27686300.0  NaN  106.715996  760.159973
2016-11-21   4614600.0   1330600.0   19652600.0  NaN  108.335266  780.000000
2016-11-22   5311300.0   1593100.0   23206700.0  NaN  108.403137  785.330017
2016-11-23   3522500.0   1477400.0   21847200.0  NaN  107.850449  780.119995
2016-11-25   1837100.0    587400.0    8409600.0  NaN  108.393433  780.369995
2016-11-28   4438800.0   2188200.0   20732600.0  NaN  108.180122  766.770020
2016-11-29   3272300.0   1616600.0   22366700.0  NaN  108.073463  762.520020
2016-11-30   4625900.0   2392900.0   34655400.0  NaN  107.162018  750.570007
2016-12-01   4666000.0   3017900.0   34542100.0  NaN  106.163315  743.650024
2016-12-02   3561300.0   1452500.0   25515700.0  NaN  106.560860  740.340027
2016-12-05   4314700.0   1394200.0   23552700.0  NaN  105.794868  759.359985
2016-12-06   3794700.0   1690700.0   19907000.0  NaN  106.609329  764.719971
2016-12-07   3684900.0   1761000.0   30809000.0  NaN  107.656517  770.419983
2016-12-08   3189600.0   1488100.0   21220800.0  NaN  108.713409  767.330017
2016-12-09   2470900.0   1821900.0   27349400.0  NaN  110.487801  768.659973
2016-12-12   2963900.0   2104100.0   20198100.0  NaN  109.857559  760.119995
2016-12-13   5285300.0   2145200.0   35718900.0  NaN  111.690132  774.340027
2016-12-14   5454800.0   1704200.0   30352700.0  NaN  111.690132  768.820007
2016-12-15   3801900.0   1626500.0   27669900.0  NaN  112.300980  761.000000
2016-12-16   4828700.0   2428300.0   42204700.0  NaN  112.446442  757.770020
2016-12-19   3113200.0   1232100.0   34338200.0  NaN  113.096069  766.000000
2016-12-20   2703600.0    951000.0   26028400.0  NaN  113.396652  771.219971
2016-12-21   2044600.0   1211300.0   17096300.0  NaN  113.503304  770.599976
2016-12-22   2543600.0    972200.0   22176600.0  NaN  112.756714  766.340027
2016-12-23   1976900.0    623400.0   12398000.0  NaN  112.979713  760.590027
2016-12-27   2638700.0    789100.0   11763200.0  NaN  113.697243  771.400024
2016-12-28   3301000.0   1153800.0   14653300.0  NaN  113.212425  772.130005
2016-12-29   3153500.0    742200.0   10181600.0  NaN  113.183334  765.150024
2016-12-30   4139400.0   1770000.0   25579900.0  NaN  112.300980  749.869995

Attributes
Symbols           GOOG       MSFT YHOO
Date
2010-01-04  311.349976  24.720928  NaN
2010-01-05  309.978882  24.728914  NaN
2010-01-06  302.164703  24.577150  NaN
2010-01-07  295.130463  24.321552  NaN
2010-01-08  299.064880  24.489288  NaN
2010-01-11  298.612823  24.177786  NaN
2010-01-12  293.332153  24.018032  NaN
2010-01-13  291.648102  24.241684  NaN
2010-01-14  293.019196  24.728914  NaN
2010-01-15  288.126007  24.649038  NaN
2010-01-19  291.911407  24.840738  NaN
2010-01-20  288.329681  24.433378  NaN
2010-01-21  289.606384  23.970112  NaN
2010-01-22  273.227905  23.131437  NaN
2010-01-25  268.255249  23.418983  NaN
2010-01-26  269.457428  23.562756  NaN
2010-01-27  269.298462  23.698549  NaN
2010-01-28  265.418701  23.291180  NaN
2010-01-29  263.257751  22.508421  NaN
2010-02-01  264.787811  22.692129  NaN
2010-02-02  263.843964  22.732069  NaN
2010-02-03  268.662598  22.867855  NaN
2010-02-04  261.687958  22.236853  NaN
2010-02-05  263.928406  22.380629  NaN
2010-02-08  265.011353  22.141001  NaN
2010-02-09  266.486755  22.372641  NaN
2010-02-10  265.498199  22.356657  NaN
2010-02-11  266.466888  22.460506  NaN
2010-02-12  264.837494  22.308741  NaN
2010-02-16  268.901062  22.750099  NaN
...                ...        ...  ...
2016-11-17  771.229980  58.306213  NaN
2016-11-18  760.539978  58.027370  NaN
2016-11-21  769.200012  58.517738  NaN
2016-11-22  768.270020  58.767731  NaN
2016-11-23  760.989990  58.075451  NaN
2016-11-25  761.679993  58.200436  NaN
2016-11-28  768.239990  58.277363  NaN
2016-11-29  770.840027  58.738884  NaN
2016-11-30  758.039978  57.940830  NaN
2016-12-01  747.919983  56.921623  NaN
2016-12-02  750.500000  56.969700  NaN
2016-12-05  762.520020  57.902378  NaN
2016-12-06  759.109985  57.642761  NaN
2016-12-07  771.190002  59.008118  NaN
2016-12-08  776.419983  58.661968  NaN
2016-12-09  789.289978  59.585018  NaN
2016-12-12  789.270020  59.777321  NaN
2016-12-13  796.099976  60.556149  NaN
2016-12-14  797.070007  60.267696  NaN
2016-12-15  797.849976  60.171543  NaN
2016-12-16  790.799988  59.902313  NaN
2016-12-19  794.200012  61.171520  NaN
2016-12-20  796.419983  61.094597  NaN
2016-12-21  794.559998  61.094597  NaN
2016-12-22  791.260010  61.104214  NaN
2016-12-23  789.909973  60.806145  NaN
2016-12-27  791.549988  60.844601  NaN
2016-12-28  785.049988  60.565762  NaN
2016-12-29  782.789978  60.479229  NaN
2016-12-30  771.820007  59.748470  NaN

[1762 rows x 30 columns]>

In [11]:
p.axes

[DatetimeIndex(['2010-01-04', '2010-01-05', '2010-01-06', '2010-01-07',
                '2010-01-08', '2010-01-11', '2010-01-12', '2010-01-13',
                '2010-01-14', '2010-01-15',
                ...
                '2016-12-16', '2016-12-19', '2016-12-20', '2016-12-21',
                '2016-12-22', '2016-12-23', '2016-12-27', '2016-12-28',
                '2016-12-29', '2016-12-30'],
               dtype='datetime64[ns]', name='Date', length=1762, freq=None),
 MultiIndex(levels=[['High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close'], ['AAPL', 'AMZN', 'GOOG', 'MSFT', 'YHOO']],
            labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5], [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]],
            names=['Attributes', 'Symbols'])]

In [13]:
p.dtypes

Attributes  Symbols
High        AAPL       float64
            AMZN       float64
            GOOG       float64
            MSFT       float64
            YHOO       float64
Low         AAPL       float64
            AMZN       float64
            GOOG       float64
            MSFT       float64
            YHOO       float64
Open        AAPL       float64
            AMZN       float64
            GOOG       float64
            MSFT       float64
            YHOO       float64
Close       AAPL       float64
            AMZN       float64
            GOOG       float64
            MSFT       float64
            YHOO       float64
Volume      AAPL       float64
            AMZN       float64
            GOOG       float64
            MSFT       float64
            YHOO       float64
Adj Close   AAPL       float64
            AMZN       float64
            GOOG       float64
            MSFT       float64
            YHOO       float64
dtype: object

In [14]:
p.ndim

2

In [15]:
p.shape

(1762, 30)

In [16]:
p.size

52860

In [17]:
p.values

array([[ 30.6428566 , 136.61000061, 312.72103882, ..., 311.34997559,
         24.72092819,          nan],
       [ 30.79857063, 135.47999573, 311.89144897, ..., 309.97888184,
         24.72891426,          nan],
       [ 30.74714279, 134.72999573, 310.90783691, ..., 302.16470337,
         24.57715034,          nan],
       ...,
       [118.01999664, 780.        , 794.22998047, ..., 785.04998779,
         60.56576157,          nan],
       [117.11000061, 773.40002441, 785.92999268, ..., 782.78997803,
         60.47922897,          nan],
       [117.19999695, 767.40002441, 782.7800293 , ..., 771.82000732,
         59.74847031,          nan]])

In [19]:
p["Open"].head()

Symbols          AAPL        AMZN        GOOG       MSFT  YHOO
Date
2010-01-04  30.490000  136.250000  311.449310  30.620001   NaN
2010-01-05  30.657143  133.429993  311.563568  30.850000   NaN
2010-01-06  30.625713  134.600006  310.907837  30.879999   NaN
2010-01-07  30.250000  132.009995  302.731018  30.629999   NaN
2010-01-08  30.042856  130.559998  294.087250  30.280001   NaN

In [22]:
p.Volume.head()

Symbols            AAPL        AMZN        GOOG        MSFT  YHOO
Date
2010-01-04  123432400.0   7599900.0   3937800.0  38409100.0   NaN
2010-01-05  150476200.0   8851900.0   6048500.0  49749600.0   NaN
2010-01-06  138040000.0   7178800.0   8009000.0  58182400.0   NaN
2010-01-07  119282800.0  11030200.0  12912000.0  50559700.0   NaN
2010-01-08  111902700.0   9830500.0   9509900.0  51197400.0   NaN

In [28]:
companies = ["MSFT", "GOOG", "AAPL", "YHOO", "AMZN"]
p = data.DataReader(name=companies, data_source="yahoo", start="2010-01-01", end="2016-12-31")
p.head(3)

Attributes       High                                            Low  \
Symbols          AAPL        AMZN        GOOG   MSFT YHOO       AAPL
Date
2010-01-04  30.642857  136.610001  312.721039  31.10  NaN  30.340000
2010-01-05  30.798571  135.479996  311.891449  31.10  NaN  30.464285
2010-01-06  30.747143  134.729996  310.907837  31.08  NaN  30.107143

Attributes                                         ...        Volume  \
Symbols           AMZN        GOOG       MSFT YHOO ...          AAPL
Date                                               ...
2010-01-04  133.139999  310.103088  30.590000  NaN ...   123432400.0
2010-01-05  131.809998  308.761810  30.639999  NaN ...   150476200.0
2010-01-06  131.649994  301.220856  30.520000  NaN ...   138040000.0

Attributes                                         Adj Close              \
Symbols          AMZN       GOOG        MSFT YHOO       AAPL        AMZN
Date
2010-01-04  7599900.0  3937800.0  38409100.0  NaN  20.473503  133.899994
2010-01-05  8851900.0  6048500.0  49749600.0  NaN  20.508902  134.690002
2010-01-06  7178800.0  8009000.0  58182400.0  NaN  20.182680  132.250000

Attributes
Symbols           GOOG       MSFT YHOO
Date
2010-01-04  311.349976  24.720928  NaN
2010-01-05  309.978882  24.728914  NaN
2010-01-06  302.164703  24.577150  NaN

[3 rows x 30 columns]

In [43]:
p.loc["2010-01-04", "Close"]

Symbols
AAPL     30.572857
AMZN    133.899994
GOOG    311.349976
MSFT     30.950001
YHOO           NaN
Name: 2010-01-04 00:00:00, dtype: float64

In [41]:
p.iloc[200, 3]

25.3700008392334

In [44]:
companies = ["MSFT", "GOOG", "AAPL", "YHOO", "AMZN"]
p = data.DataReader(name=companies, data_source="yahoo", start="2010-01-01", end="2016-12-31")
p.head(3)

Attributes       High                                            Low  \
Symbols          AAPL        AMZN        GOOG   MSFT YHOO       AAPL
Date
2010-01-04  30.642857  136.610001  312.721039  31.10  NaN  30.340000
2010-01-05  30.798571  135.479996  311.891449  31.10  NaN  30.464285
2010-01-06  30.747143  134.729996  310.907837  31.08  NaN  30.107143

Attributes                                         ...        Volume  \
Symbols           AMZN        GOOG       MSFT YHOO ...          AAPL
Date                                               ...
2010-01-04  133.139999  310.103088  30.590000  NaN ...   123432400.0
2010-01-05  131.809998  308.761810  30.639999  NaN ...   150476200.0
2010-01-06  131.649994  301.220856  30.520000  NaN ...   138040000.0

Attributes                                         Adj Close              \
Symbols          AMZN       GOOG        MSFT YHOO       AAPL        AMZN
Date
2010-01-04  7599900.0  3937800.0  38409100.0  NaN  20.473503  133.899994
2010-01-05  8851900.0  6048500.0  49749600.0  NaN  20.508902  134.690002
2010-01-06  7178800.0  8009000.0  58182400.0  NaN  20.182680  132.250000

Attributes
Symbols           GOOG       MSFT YHOO
Date
2010-01-04  311.349976  24.720928  NaN
2010-01-05  309.978882  24.728914  NaN
2010-01-06  302.164703  24.577150  NaN

[3 rows x 30 columns]

In [50]:
df = p.stack()
df.head()

Attributes                High         Low        Open       Close  \
Date       Symbols
2010-01-04 AAPL      30.642857   30.340000   30.490000   30.572857
           AMZN     136.610001  133.139999  136.250000  133.899994
           GOOG     312.721039  310.103088  311.449310  311.349976
           MSFT      31.100000   30.590000   30.620001   30.950001
2010-01-05 AAPL      30.798571   30.464285   30.657143   30.625713

Attributes               Volume   Adj Close
Date       Symbols
2010-01-04 AAPL     123432400.0   20.473503
           AMZN       7599900.0  133.899994
           GOOG       3937800.0  311.349976
           MSFT      38409100.0   24.720928
2010-01-05 AAPL     150476200.0   20.508902

In [52]:
p2 = df.to_panel()
p2

/Users/ninja/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning:
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  """Entry point for launching an IPython kernel.

<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 1762 (major_axis) x 5 (minor_axis)
Items axis: High to Adj Close
Major_axis axis: 2010-01-04 00:00:00 to 2016-12-30 00:00:00
Minor_axis axis: AAPL to YHOO

In [54]:
companies = ["MSFT", "GOOG", "AAPL", "YHOO", "AMZN"]
p = data.DataReader(name=companies, data_source="yahoo", start="2010-01-01", end="2016-12-31")
p.head(3)

Attributes       High                                            Low  \
Symbols          AAPL        AMZN        GOOG   MSFT YHOO       AAPL
Date
2010-01-04  30.642857  136.610001  312.721039  31.10  NaN  30.340000
2010-01-05  30.798571  135.479996  311.891449  31.10  NaN  30.464285
2010-01-06  30.747143  134.729996  310.907837  31.08  NaN  30.107143

Attributes                                         ...        Volume  \
Symbols           AMZN        GOOG       MSFT YHOO ...          AAPL
Date                                               ...
2010-01-04  133.139999  310.103088  30.590000  NaN ...   123432400.0
2010-01-05  131.809998  308.761810  30.639999  NaN ...   150476200.0
2010-01-06  131.649994  301.220856  30.520000  NaN ...   138040000.0

Attributes                                         Adj Close              \
Symbols          AMZN       GOOG        MSFT YHOO       AAPL        AMZN
Date
2010-01-04  7599900.0  3937800.0  38409100.0  NaN  20.473503  133.899994
2010-01-05  8851900.0  6048500.0  49749600.0  NaN  20.508902  134.690002
2010-01-06  7178800.0  8009000.0  58182400.0  NaN  20.182680  132.250000

Attributes
Symbols           GOOG       MSFT YHOO
Date
2010-01-04  311.349976  24.720928  NaN
2010-01-05  309.978882  24.728914  NaN
2010-01-06  302.164703  24.577150  NaN

[3 rows x 30 columns]

In [55]:
p.items

<bound method DataFrame.iteritems of Attributes        High                                                 Low  \
Symbols           AAPL        AMZN        GOOG       MSFT YHOO        AAPL
Date
2010-01-04   30.642857  136.610001  312.721039  31.100000  NaN   30.340000
2010-01-05   30.798571  135.479996  311.891449  31.100000  NaN   30.464285
2010-01-06   30.747143  134.729996  310.907837  31.080000  NaN   30.107143
2010-01-07   30.285715  132.320007  303.029083  30.700001  NaN   29.864286
2010-01-08   30.285715  133.679993  299.675903  30.879999  NaN   29.865715
2010-01-11   30.428572  132.800003  300.276978  30.760000  NaN   29.778572
2010-01-12   29.967142  129.820007  297.147339  30.400000  NaN   29.488571
2010-01-13   30.132856  129.710007  292.288940  30.520000  NaN   29.157143
2010-01-14   30.065714  130.380005  295.180145  31.100000  NaN   29.860001
2010-01-15   30.228571  129.649994  294.862213  31.240000  NaN   29.410000
2010-01-19   30.741428  128.000000  293.302338  31.240000  NaN   29.605715
2010-01-20   30.792856  129.199997  291.096710  30.940001  NaN   29.928572
2010-01-21   30.472857  128.149994  291.513977  30.719999  NaN   29.601429
2010-01-22   29.642857  127.669998  283.456390  30.200001  NaN   28.165714
2010-01-25   29.242857  122.279999  273.163330  29.660000  NaN   28.598572
2010-01-26   30.530001  122.980003  273.024231  29.850000  NaN   28.940001
2010-01-27   30.082857  123.330002  272.055542  29.820000  NaN   28.504286
2010-01-28   29.357143  127.199997  271.732635  29.870001  NaN   28.385714
2010-01-29   28.885714  131.850006  268.747070  29.920000  NaN   27.178572
2010-02-01   28.000000  124.860001  266.173798  28.480000  NaN   27.328571
2010-02-02   28.045713  118.980003  265.751556  28.500000  NaN   27.625713
2010-02-03   28.600000  119.610001  269.298462  28.790001  NaN   27.774286
2010-02-04   28.338572  120.330002  267.261719  28.500000  NaN   27.367144
2010-02-05   28.000000  117.650002  265.026245  28.280001  NaN   27.264286
2010-02-08   28.268572  121.000000  269.248810  28.080000  NaN   27.714285
2010-02-09   28.214285  119.089996  269.015320  28.340000  NaN   27.821428
2010-02-10   28.085714  118.610001  267.157410  28.240000  NaN   27.751429
2010-02-11   28.535715  120.419998  268.498688  28.400000  NaN   27.722857
2010-02-12   28.805714  119.940002  266.839478  28.059999  NaN   27.928572
2010-02-16   29.098572  120.500000  270.306915  28.370001  NaN   28.788572
...                ...         ...         ...        ...  ...         ...
2016-11-17  110.349998  757.500000  772.700012  60.950001  NaN  108.830002
2016-11-18  110.540001  767.739990  775.000000  61.139999  NaN  109.660004
2016-11-21  111.989998  780.349976  769.700012  60.970001  NaN  110.010002
2016-11-22  112.419998  792.400024  776.960022  61.259998  NaN  111.400002
2016-11-23  111.510002  781.750000  768.283020  61.099998  NaN  110.330002
2016-11-25  111.870003  786.750000  765.000000  60.529999  NaN  110.949997
2016-11-28  112.470001  777.000000  779.530029  61.020000  NaN  111.389999
2016-11-29  112.029999  769.890015  778.500000  61.410000  NaN  110.070000
2016-11-30  112.199997  768.090027  772.989990  61.180000  NaN  110.269997
2016-12-01  110.940002  753.369995  759.849976  60.150002  NaN  109.029999
2016-12-02  110.089996  748.489990  754.000000  59.470001  NaN  108.849998
2016-12-05  110.029999  761.489990  763.900024  60.590000  NaN  108.250000
2016-12-06  110.360001  768.239990  768.830017  60.459999  NaN  109.190002
2016-12-07  111.190002  770.419983  771.359985  61.380001  NaN  109.160004
2016-12-08  112.430000  773.789978  778.179993  61.580002  NaN  110.599998
2016-12-09  114.699997  770.250000  789.429993  61.990002  NaN  112.309998
2016-12-12  115.000000  766.890015  791.250000  62.299999  NaN  112.489998
2016-12-13  115.919998  782.460022  804.380005  63.419998  NaN  113.750000
2016-12-14  116.199997  780.859985  804.000000  63.450001  NaN  114.980003
2016-12-15  116.730003  769.099976  803.000000  63.150002  NaN  115.230003
2016-12-16  116.500000  765.130005  800.856018  62.950001  NaN  115.650002
2016-12-19  117.379997  770.500000  797.659973  63.770000  NaN  115.750000
2016-12-20  117.500000  774.390015  798.650024  63.799999  NaN  116.680000
2016-12-21  117.400002  771.219971  796.676025  63.700001  NaN  116.779999
2016-12-22  116.510002  771.210022  793.320007  64.099998  NaN  115.639999
2016-12-23  116.519997  766.500000  792.739990  63.540001  NaN  115.589996
2016-12-27  117.800003  774.650024  797.859985  64.070000  NaN  116.489998
2016-12-28  118.019997  780.000000  794.229980  63.400002  NaN  116.199997
2016-12-29  117.110001  773.400024  785.929993  63.200001  NaN  116.400002
2016-12-30  117.199997  767.400024  782.780029  62.990002  NaN  115.430000

Attributes                                         ...        Volume  \
Symbols           AMZN        GOOG       MSFT YHOO ...          AAPL
Date                                               ...
2010-01-04  133.139999  310.103088  30.590000  NaN ...   123432400.0
2010-01-05  131.809998  308.761810  30.639999  NaN ...   150476200.0
2010-01-06  131.649994  301.220856  30.520000  NaN ...   138040000.0
2010-01-07  128.800003  294.410156  30.190001  NaN ...   119282800.0
2010-01-08  129.029999  292.651581  30.240000  NaN ...   111902700.0
2010-01-11  129.210007  295.100647  30.120001  NaN ...   115557400.0
2010-01-12  126.550003  292.100159  29.910000  NaN ...   148614900.0
2010-01-13  125.750000  285.095734  30.010000  NaN ...   151473000.0
2010-01-14  126.400002  289.521942  30.260000  NaN ...   108223500.0
2010-01-15  127.059998  287.152344  30.709999  NaN ...   148516900.0
2010-01-19  124.330002  286.283020  30.680000  NaN ...   182501900.0
2010-01-20  125.080002  285.786224  30.309999  NaN ...   153038200.0
2010-01-21  125.000000  284.276062  30.000000  NaN ...   152038600.0
2010-01-22  120.760002  265.701874  28.840000  NaN ...   220441900.0
2010-01-25  118.120003  266.024780  29.100000  NaN ...   266424900.0
2010-01-26  119.059998  266.412231  29.090000  NaN ...   466777500.0
2010-01-27  118.800003  265.925415  29.020000  NaN ...   430642100.0
2010-01-28  122.800003  263.585632  28.889999  NaN ...   293375600.0
2010-01-29  124.139999  261.106750  27.660000  NaN ...   311488100.0
2010-02-01  113.820000  263.436584  27.920000  NaN ...   187469100.0
2010-02-02  114.400002  262.100281  28.139999  NaN ...   174585600.0
2010-02-03  116.559998  262.408295  28.120001  NaN ...   153832000.0
2010-02-04  115.739998  261.081909  27.809999  NaN ...   189413000.0
2010-02-05  114.099998  259.541931  27.570000  NaN ...   212576700.0
2010-02-08  116.559998  264.047638  27.570000  NaN ...   119567700.0
2010-02-09  117.000000  265.806183  27.750000  NaN ...   158221700.0
2010-02-10  116.000000  262.140045  27.840000  NaN ...    92590400.0
2010-02-11  116.500000  263.039185  27.700001  NaN ...   137586400.0
2010-02-12  117.500000  263.535950  27.580000  NaN ...   163867200.0
2010-02-16  117.180000  265.423676  28.020000  NaN ...   135934400.0
...                ...         ...        ...  ... ...           ...
2016-11-17  748.000000  764.229980  59.970001  NaN ...    27632000.0
2016-11-18  757.640015  760.000000  60.299999  NaN ...    28428900.0
2016-11-21  765.109985  760.599976  60.419998  NaN ...    29264600.0
2016-11-22  781.000000  767.000000  60.810001  NaN ...    25965500.0
2016-11-23  773.119995  755.250000  60.250000  NaN ...    27426400.0
2016-11-25  777.900024  760.520020  60.130001  NaN ...    11475900.0
2016-11-28  764.239990  759.799988  60.209999  NaN ...    27194000.0
2016-11-29  761.320007  768.239990  60.520000  NaN ...    28528800.0
2016-11-30  750.250000  754.830017  60.220001  NaN ...    36162300.0
2016-12-01  738.030029  737.025024  58.939999  NaN ...    37086900.0
2016-12-02  736.700012  743.099976  58.799999  NaN ...    26528000.0
2016-12-05  742.000000  752.900024  59.560001  NaN ...    34324500.0
2016-12-06  757.250000  757.340027  59.799999  NaN ...    26195500.0
2016-12-07  755.820007  755.799988  59.799999  NaN ...    29998700.0
2016-12-08  765.190002  767.229980  60.840000  NaN ...    27068300.0
2016-12-09  765.340027  779.020996  61.130001  NaN ...    34402600.0
2016-12-12  757.200012  784.354980  61.720001  NaN ...    26374400.0
2016-12-13  762.000000  793.340027  62.240002  NaN ...    43733800.0
2016-12-14  762.809998  794.010010  62.529999  NaN ...    34031800.0
2016-12-15  760.309998  792.919983  62.299999  NaN ...    46524500.0
2016-12-16  754.000000  790.289978  62.119999  NaN ...    44351100.0
2016-12-19  756.159973  786.270020  62.419998  NaN ...    27779400.0
2016-12-20  767.710022  793.270020  63.029999  NaN ...    21425000.0
2016-12-21  765.700012  787.099976  63.119999  NaN ...    23783200.0
2016-12-22  763.020020  788.580017  63.410000  NaN ...    26085900.0
2016-12-23  757.989990  787.280029  62.799999  NaN ...    14249500.0
2016-12-27  761.200012  787.656982  63.209999  NaN ...    18296900.0
2016-12-28  770.500000  783.200012  62.830002  NaN ...    20905900.0
2016-12-29  760.849976  778.919983  62.730000  NaN ...    15039500.0
2016-12-30  748.280029  770.409973  62.029999  NaN ...    30586300.0

Attributes                                             Adj Close              \
Symbols           AMZN        GOOG         MSFT YHOO        AAPL        AMZN
Date
2010-01-04   7599900.0   3937800.0   38409100.0  NaN   20.473503  133.899994
2010-01-05   8851900.0   6048500.0   49749600.0  NaN   20.508902  134.690002
2010-01-06   7178800.0   8009000.0   58182400.0  NaN   20.182680  132.250000
2010-01-07  11030200.0  12912000.0   50559700.0  NaN   20.145369  130.000000
2010-01-08   9830500.0   9509900.0   51197400.0  NaN   20.279305  133.520004
2010-01-11   8779400.0  14519600.0   68754700.0  NaN   20.100410  130.309998
2010-01-12   9096300.0   9769600.0   65912100.0  NaN   19.871763  127.349998
2010-01-13  10723200.0  13077600.0   51863500.0  NaN   20.152065  129.110001
2010-01-14   9774900.0   8535300.0   63228100.0  NaN   20.035355  127.349998
2010-01-15  15376500.0  10939600.0   79913200.0  NaN   19.700523  127.139999
2010-01-19   8892600.0   8689500.0   46575700.0  NaN   20.572037  127.610001
2010-01-20   9074700.0   6543600.0   54849500.0  NaN   20.255390  125.779999
2010-01-21   9970600.0  12697400.0   73086700.0  NaN   19.905249  126.620003
2010-01-22  11568900.0  13689200.0  102004600.0  NaN   18.917973  121.430000
2010-01-25  12023900.0   8897200.0   63373000.0  NaN   19.426920  120.309998
2010-01-26   9559000.0   8767600.0   66639900.0  NaN   19.701479  119.480003
2010-01-27  14765300.0   7980200.0   63949500.0  NaN   19.887072  122.750000
2010-01-28  27293100.0   6500100.0  117513700.0  NaN   19.065300  126.029999
2010-01-29  29471300.0   8334700.0  193888500.0  NaN   18.373636  125.410004
2010-02-01  37774400.0   4530800.0   85931100.0  NaN   18.629066  118.870003
2010-02-02  23079700.0   8245600.0   54413700.0  NaN   18.737165  118.120003
2010-02-03  12405900.0   6037000.0   61397900.0  NaN   19.059557  119.099998
2010-02-04  12784000.0   6799200.0   77850000.0  NaN   18.372683  115.940002
2010-02-05  11024800.0   6353000.0   80960100.0  NaN   18.698900  117.389999
2010-02-08   9890200.0   5423500.0   52820600.0  NaN   18.570709  116.830002
2010-02-09   9223000.0   5675700.0   59195800.0  NaN   18.768732  118.029999
2010-02-10   6233200.0   5383700.0   48591300.0  NaN   18.666370  117.360001
2010-02-11   8343500.0   4851300.0   65993700.0  NaN   19.005989  120.089996
2010-02-12   8073500.0   4589000.0   81117200.0  NaN   19.169575  119.660004
2010-02-16   8932700.0   7356200.0   51935600.0  NaN   19.458488  117.529999
...                ...         ...          ...  ...         ...         ...
2016-11-17   3690100.0   1304000.0   32132700.0  NaN  106.609329  756.400024
2016-11-18   4373400.0   1547100.0   27686300.0  NaN  106.715996  760.159973
2016-11-21   4614600.0   1330600.0   19652600.0  NaN  108.335266  780.000000
2016-11-22   5311300.0   1593100.0   23206700.0  NaN  108.403137  785.330017
2016-11-23   3522500.0   1477400.0   21847200.0  NaN  107.850449  780.119995
2016-11-25   1837100.0    587400.0    8409600.0  NaN  108.393433  780.369995
2016-11-28   4438800.0   2188200.0   20732600.0  NaN  108.180122  766.770020
2016-11-29   3272300.0   1616600.0   22366700.0  NaN  108.073463  762.520020
2016-11-30   4625900.0   2392900.0   34655400.0  NaN  107.162018  750.570007
2016-12-01   4666000.0   3017900.0   34542100.0  NaN  106.163315  743.650024
2016-12-02   3561300.0   1452500.0   25515700.0  NaN  106.560860  740.340027
2016-12-05   4314700.0   1394200.0   23552700.0  NaN  105.794868  759.359985
2016-12-06   3794700.0   1690700.0   19907000.0  NaN  106.609329  764.719971
2016-12-07   3684900.0   1761000.0   30809000.0  NaN  107.656517  770.419983
2016-12-08   3189600.0   1488100.0   21220800.0  NaN  108.713409  767.330017
2016-12-09   2470900.0   1821900.0   27349400.0  NaN  110.487801  768.659973
2016-12-12   2963900.0   2104100.0   20198100.0  NaN  109.857559  760.119995
2016-12-13   5285300.0   2145200.0   35718900.0  NaN  111.690132  774.340027
2016-12-14   5454800.0   1704200.0   30352700.0  NaN  111.690132  768.820007
2016-12-15   3801900.0   1626500.0   27669900.0  NaN  112.300980  761.000000
2016-12-16   4828700.0   2428300.0   42204700.0  NaN  112.446442  757.770020
2016-12-19   3113200.0   1232100.0   34338200.0  NaN  113.096069  766.000000
2016-12-20   2703600.0    951000.0   26028400.0  NaN  113.396652  771.219971
2016-12-21   2044600.0   1211300.0   17096300.0  NaN  113.503304  770.599976
2016-12-22   2543600.0    972200.0   22176600.0  NaN  112.756714  766.340027
2016-12-23   1976900.0    623400.0   12398000.0  NaN  112.979713  760.590027
2016-12-27   2638700.0    789100.0   11763200.0  NaN  113.697243  771.400024
2016-12-28   3301000.0   1153800.0   14653300.0  NaN  113.212425  772.130005
2016-12-29   3153500.0    742200.0   10181600.0  NaN  113.183334  765.150024
2016-12-30   4139400.0   1770000.0   25579900.0  NaN  112.300980  749.869995

Attributes
Symbols           GOOG       MSFT YHOO
Date
2010-01-04  311.349976  24.720928  NaN
2010-01-05  309.978882  24.728914  NaN
2010-01-06  302.164703  24.577150  NaN
2010-01-07  295.130463  24.321552  NaN
2010-01-08  299.064880  24.489288  NaN
2010-01-11  298.612823  24.177786  NaN
2010-01-12  293.332153  24.018032  NaN
2010-01-13  291.648102  24.241684  NaN
2010-01-14  293.019196  24.728914  NaN
2010-01-15  288.126007  24.649038  NaN
2010-01-19  291.911407  24.840738  NaN
2010-01-20  288.329681  24.433378  NaN
2010-01-21  289.606384  23.970112  NaN
2010-01-22  273.227905  23.131437  NaN
2010-01-25  268.255249  23.418983  NaN
2010-01-26  269.457428  23.562756  NaN
2010-01-27  269.298462  23.698549  NaN
2010-01-28  265.418701  23.291180  NaN
2010-01-29  263.257751  22.508421  NaN
2010-02-01  264.787811  22.692129  NaN
2010-02-02  263.843964  22.732069  NaN
2010-02-03  268.662598  22.867855  NaN
2010-02-04  261.687958  22.236853  NaN
2010-02-05  263.928406  22.380629  NaN
2010-02-08  265.011353  22.141001  NaN
2010-02-09  266.486755  22.372641  NaN
2010-02-10  265.498199  22.356657  NaN
2010-02-11  266.466888  22.460506  NaN
2010-02-12  264.837494  22.308741  NaN
2010-02-16  268.901062  22.750099  NaN
...                ...        ...  ...
2016-11-17  771.229980  58.306213  NaN
2016-11-18  760.539978  58.027370  NaN
2016-11-21  769.200012  58.517738  NaN
2016-11-22  768.270020  58.767731  NaN
2016-11-23  760.989990  58.075451  NaN
2016-11-25  761.679993  58.200436  NaN
2016-11-28  768.239990  58.277363  NaN
2016-11-29  770.840027  58.738884  NaN
2016-11-30  758.039978  57.940830  NaN
2016-12-01  747.919983  56.921623  NaN
2016-12-02  750.500000  56.969700  NaN
2016-12-05  762.520020  57.902378  NaN
2016-12-06  759.109985  57.642761  NaN
2016-12-07  771.190002  59.008118  NaN
2016-12-08  776.419983  58.661968  NaN
2016-12-09  789.289978  59.585018  NaN
2016-12-12  789.270020  59.777321  NaN
2016-12-13  796.099976  60.556149  NaN
2016-12-14  797.070007  60.267696  NaN
2016-12-15  797.849976  60.171543  NaN
2016-12-16  790.799988  59.902313  NaN
2016-12-19  794.200012  61.171520  NaN
2016-12-20  796.419983  61.094597  NaN
2016-12-21  794.559998  61.094597  NaN
2016-12-22  791.260010  61.104214  NaN
2016-12-23  789.909973  60.806145  NaN
2016-12-27  791.549988  60.844601  NaN
2016-12-28  785.049988  60.565762  NaN
2016-12-29  782.789978  60.479229  NaN
2016-12-30  771.820007  59.748470  NaN

[1762 rows x 30 columns]>

In [58]:
p["High"].head()

Symbols          AAPL        AMZN        GOOG       MSFT  YHOO
Date
2010-01-04  30.642857  136.610001  312.721039  31.100000   NaN
2010-01-05  30.798571  135.479996  311.891449  31.100000   NaN
2010-01-06  30.747143  134.729996  310.907837  31.080000   NaN
2010-01-07  30.285715  132.320007  303.029083  30.700001   NaN
2010-01-08  30.285715  133.679993  299.675903  30.879999   NaN

In [73]:
p.transpose()

Date                  2010-01-04    2010-01-05    2010-01-06    2010-01-07  \
Attributes Symbols
High       AAPL     3.064286e+01  3.079857e+01  3.074714e+01  3.028572e+01
           AMZN     1.366100e+02  1.354800e+02  1.347300e+02  1.323200e+02
           GOOG     3.127210e+02  3.118914e+02  3.109078e+02  3.030291e+02
           MSFT     3.110000e+01  3.110000e+01  3.108000e+01  3.070000e+01
           YHOO              NaN           NaN           NaN           NaN
Low        AAPL     3.034000e+01  3.046428e+01  3.010714e+01  2.986429e+01
           AMZN     1.331400e+02  1.318100e+02  1.316500e+02  1.288000e+02
           GOOG     3.101031e+02  3.087618e+02  3.012209e+02  2.944102e+02
           MSFT     3.059000e+01  3.064000e+01  3.052000e+01  3.019000e+01
           YHOO              NaN           NaN           NaN           NaN
Open       AAPL     3.049000e+01  3.065714e+01  3.062571e+01  3.025000e+01
           AMZN     1.362500e+02  1.334300e+02  1.346000e+02  1.320100e+02
           GOOG     3.114493e+02  3.115636e+02  3.109078e+02  3.027310e+02
           MSFT     3.062000e+01  3.085000e+01  3.088000e+01  3.063000e+01
           YHOO              NaN           NaN           NaN           NaN
Close      AAPL     3.057286e+01  3.062571e+01  3.013857e+01  3.008286e+01
           AMZN     1.339000e+02  1.346900e+02  1.322500e+02  1.300000e+02
           GOOG     3.113500e+02  3.099789e+02  3.021647e+02  2.951305e+02
           MSFT     3.095000e+01  3.096000e+01  3.077000e+01  3.045000e+01
           YHOO              NaN           NaN           NaN           NaN
Volume     AAPL     1.234324e+08  1.504762e+08  1.380400e+08  1.192828e+08
           AMZN     7.599900e+06  8.851900e+06  7.178800e+06  1.103020e+07
           GOOG     3.937800e+06  6.048500e+06  8.009000e+06  1.291200e+07
           MSFT     3.840910e+07  4.974960e+07  5.818240e+07  5.055970e+07
           YHOO              NaN           NaN           NaN           NaN
Adj Close  AAPL     2.047350e+01  2.050890e+01  2.018268e+01  2.014537e+01
           AMZN     1.339000e+02  1.346900e+02  1.322500e+02  1.300000e+02
           GOOG     3.113500e+02  3.099789e+02  3.021647e+02  2.951305e+02
           MSFT     2.472093e+01  2.472891e+01  2.457715e+01  2.432155e+01
           YHOO              NaN           NaN           NaN           NaN

Date                  2010-01-08    2010-01-11    2010-01-12    2010-01-13  \
Attributes Symbols
High       AAPL     3.028572e+01  3.042857e+01  2.996714e+01  3.013286e+01
           AMZN     1.336800e+02  1.328000e+02  1.298200e+02  1.297100e+02
           GOOG     2.996759e+02  3.002770e+02  2.971473e+02  2.922889e+02
           MSFT     3.088000e+01  3.076000e+01  3.040000e+01  3.052000e+01
           YHOO              NaN           NaN           NaN           NaN
Low        AAPL     2.986572e+01  2.977857e+01  2.948857e+01  2.915714e+01
           AMZN     1.290300e+02  1.292100e+02  1.265500e+02  1.257500e+02
           GOOG     2.926516e+02  2.951006e+02  2.921002e+02  2.850957e+02
           MSFT     3.024000e+01  3.012000e+01  2.991000e+01  3.001000e+01
           YHOO              NaN           NaN           NaN           NaN
Open       AAPL     3.004286e+01  3.040000e+01  2.988428e+01  2.969571e+01
           AMZN     1.305600e+02  1.326200e+02  1.289900e+02  1.279000e+02
           GOOG     2.940872e+02  3.002770e+02  2.968940e+02  2.863824e+02
           MSFT     3.028000e+01  3.071000e+01  3.015000e+01  3.026000e+01
           YHOO              NaN           NaN           NaN           NaN
Close      AAPL     3.028286e+01  3.001571e+01  2.967429e+01  3.009286e+01
           AMZN     1.335200e+02  1.303100e+02  1.273500e+02  1.291100e+02
           GOOG     2.990649e+02  2.986128e+02  2.933322e+02  2.916481e+02
           MSFT     3.066000e+01  3.027000e+01  3.007000e+01  3.035000e+01
           YHOO              NaN           NaN           NaN           NaN
Volume     AAPL     1.119027e+08  1.155574e+08  1.486149e+08  1.514730e+08
           AMZN     9.830500e+06  8.779400e+06  9.096300e+06  1.072320e+07
           GOOG     9.509900e+06  1.451960e+07  9.769600e+06  1.307760e+07
           MSFT     5.119740e+07  6.875470e+07  6.591210e+07  5.186350e+07
           YHOO              NaN           NaN           NaN           NaN
Adj Close  AAPL     2.027930e+01  2.010041e+01  1.987176e+01  2.015207e+01
           AMZN     1.335200e+02  1.303100e+02  1.273500e+02  1.291100e+02
           GOOG     2.990649e+02  2.986128e+02  2.933322e+02  2.916481e+02
           MSFT     2.448929e+01  2.417779e+01  2.401803e+01  2.424168e+01
           YHOO              NaN           NaN           NaN           NaN

Date                  2010-01-14    2010-01-15      ...         2016-12-16  \
Attributes Symbols                                  ...
High       AAPL     3.006571e+01  3.022857e+01      ...       1.165000e+02
           AMZN     1.303800e+02  1.296500e+02      ...       7.651300e+02
           GOOG     2.951801e+02  2.948622e+02      ...       8.008560e+02
           MSFT     3.110000e+01  3.124000e+01      ...       6.295000e+01
           YHOO              NaN           NaN      ...                NaN
Low        AAPL     2.986000e+01  2.941000e+01      ...       1.156500e+02
           AMZN     1.264000e+02  1.270600e+02      ...       7.540000e+02
           GOOG     2.895219e+02  2.871523e+02      ...       7.902900e+02
           MSFT     3.026000e+01  3.071000e+01      ...       6.212000e+01
           YHOO              NaN           NaN      ...                NaN
Open       AAPL     3.001571e+01  3.013286e+01      ...       1.164700e+02
           AMZN     1.291400e+02  1.291800e+02      ...       7.650000e+02
           GOOG     2.900634e+02  2.947529e+02      ...       8.004000e+02
           MSFT     3.031000e+01  3.108000e+01      ...       6.295000e+01
           YHOO              NaN           NaN      ...                NaN
Close      AAPL     2.991857e+01  2.941857e+01      ...       1.159700e+02
           AMZN     1.273500e+02  1.271400e+02      ...       7.577700e+02
           GOOG     2.930192e+02  2.881260e+02      ...       7.908000e+02
           MSFT     3.096000e+01  3.086000e+01      ...       6.230000e+01
           YHOO              NaN           NaN      ...                NaN
Volume     AAPL     1.082235e+08  1.485169e+08      ...       4.435110e+07
           AMZN     9.774900e+06  1.537650e+07      ...       4.828700e+06
           GOOG     8.535300e+06  1.093960e+07      ...       2.428300e+06
           MSFT     6.322810e+07  7.991320e+07      ...       4.220470e+07
           YHOO              NaN           NaN      ...                NaN
Adj Close  AAPL     2.003535e+01  1.970052e+01      ...       1.124464e+02
           AMZN     1.273500e+02  1.271400e+02      ...       7.577700e+02
           GOOG     2.930192e+02  2.881260e+02      ...       7.908000e+02
           MSFT     2.472891e+01  2.464904e+01      ...       5.990231e+01
           YHOO              NaN           NaN      ...                NaN

Date                  2016-12-19    2016-12-20    2016-12-21    2016-12-22  \
Attributes Symbols
High       AAPL     1.173800e+02  1.175000e+02  1.174000e+02  1.165100e+02
           AMZN     7.705000e+02  7.743900e+02  7.712200e+02  7.712100e+02
           GOOG     7.976600e+02  7.986500e+02  7.966760e+02  7.933200e+02
           MSFT     6.377000e+01  6.380000e+01  6.370000e+01  6.410000e+01
           YHOO              NaN           NaN           NaN           NaN
Low        AAPL     1.157500e+02  1.166800e+02  1.167800e+02  1.156400e+02
           AMZN     7.561600e+02  7.677100e+02  7.657000e+02  7.630200e+02
           GOOG     7.862700e+02  7.932700e+02  7.871000e+02  7.885800e+02
           MSFT     6.242000e+01  6.303000e+01  6.312000e+01  6.341000e+01
           YHOO              NaN           NaN           NaN           NaN
Open       AAPL     1.158000e+02  1.167400e+02  1.168000e+02  1.163500e+02
           AMZN     7.588900e+02  7.686500e+02  7.700000e+02  7.681200e+02
           GOOG     7.902200e+02  7.967600e+02  7.958400e+02  7.923600e+02
           MSFT     6.256000e+01  6.369000e+01  6.343000e+01  6.384000e+01
           YHOO              NaN           NaN           NaN           NaN
Close      AAPL     1.166400e+02  1.169500e+02  1.170600e+02  1.162900e+02
           AMZN     7.660000e+02  7.712200e+02  7.706000e+02  7.663400e+02
           GOOG     7.942000e+02  7.964200e+02  7.945600e+02  7.912600e+02
           MSFT     6.362000e+01  6.354000e+01  6.354000e+01  6.355000e+01
           YHOO              NaN           NaN           NaN           NaN
Volume     AAPL     2.777940e+07  2.142500e+07  2.378320e+07  2.608590e+07
           AMZN     3.113200e+06  2.703600e+06  2.044600e+06  2.543600e+06
           GOOG     1.232100e+06  9.510000e+05  1.211300e+06  9.722000e+05
           MSFT     3.433820e+07  2.602840e+07  1.709630e+07  2.217660e+07
           YHOO              NaN           NaN           NaN           NaN
Adj Close  AAPL     1.130961e+02  1.133967e+02  1.135033e+02  1.127567e+02
           AMZN     7.660000e+02  7.712200e+02  7.706000e+02  7.663400e+02
           GOOG     7.942000e+02  7.964200e+02  7.945600e+02  7.912600e+02
           MSFT     6.117152e+01  6.109460e+01  6.109460e+01  6.110421e+01
           YHOO              NaN           NaN           NaN           NaN

Date                  2016-12-23    2016-12-27    2016-12-28    2016-12-29  \
Attributes Symbols
High       AAPL     1.165200e+02  1.178000e+02  1.180200e+02  1.171100e+02
           AMZN     7.665000e+02  7.746500e+02  7.800000e+02  7.734000e+02
           GOOG     7.927400e+02  7.978600e+02  7.942300e+02  7.859300e+02
           MSFT     6.354000e+01  6.407000e+01  6.340000e+01  6.320000e+01
           YHOO              NaN           NaN           NaN           NaN
Low        AAPL     1.155900e+02  1.164900e+02  1.162000e+02  1.164000e+02
           AMZN     7.579900e+02  7.612000e+02  7.705000e+02  7.608500e+02
           GOOG     7.872800e+02  7.876570e+02  7.832000e+02  7.789200e+02
           MSFT     6.280000e+01  6.321000e+01  6.283000e+01  6.273000e+01
           YHOO              NaN           NaN           NaN           NaN
Open       AAPL     1.155900e+02  1.165200e+02  1.175200e+02  1.164500e+02
           AMZN     7.645500e+02  7.634000e+02  7.762500e+02  7.724000e+02
           GOOG     7.909000e+02  7.906800e+02  7.937000e+02  7.833300e+02
           MSFT     6.345000e+01  6.321000e+01  6.340000e+01  6.286000e+01
           YHOO              NaN           NaN           NaN           NaN
Close      AAPL     1.165200e+02  1.172600e+02  1.167600e+02  1.167300e+02
           AMZN     7.605900e+02  7.714000e+02  7.721300e+02  7.651500e+02
           GOOG     7.899100e+02  7.915500e+02  7.850500e+02  7.827900e+02
           MSFT     6.324000e+01  6.328000e+01  6.299000e+01  6.290000e+01
           YHOO              NaN           NaN           NaN           NaN
Volume     AAPL     1.424950e+07  1.829690e+07  2.090590e+07  1.503950e+07
           AMZN     1.976900e+06  2.638700e+06  3.301000e+06  3.153500e+06
           GOOG     6.234000e+05  7.891000e+05  1.153800e+06  7.422000e+05
           MSFT     1.239800e+07  1.176320e+07  1.465330e+07  1.018160e+07
           YHOO              NaN           NaN           NaN           NaN
Adj Close  AAPL     1.129797e+02  1.136972e+02  1.132124e+02  1.131833e+02
           AMZN     7.605900e+02  7.714000e+02  7.721300e+02  7.651500e+02
           GOOG     7.899100e+02  7.915500e+02  7.850500e+02  7.827900e+02
           MSFT     6.080614e+01  6.084460e+01  6.056576e+01  6.047923e+01
           YHOO              NaN           NaN           NaN           NaN

Date                  2016-12-30
Attributes Symbols
High       AAPL     1.172000e+02
           AMZN     7.674000e+02
           GOOG     7.827800e+02
           MSFT     6.299000e+01
           YHOO              NaN
Low        AAPL     1.154300e+02
           AMZN     7.482800e+02
           GOOG     7.704100e+02
           MSFT     6.203000e+01
           YHOO              NaN
Open       AAPL     1.166500e+02
           AMZN     7.664700e+02
           GOOG     7.827500e+02
           MSFT     6.296000e+01
           YHOO              NaN
Close      AAPL     1.158200e+02
           AMZN     7.498700e+02
           GOOG     7.718200e+02
           MSFT     6.214000e+01
           YHOO              NaN
Volume     AAPL     3.058630e+07
           AMZN     4.139400e+06
           GOOG     1.770000e+06
           MSFT     2.557990e+07
           YHOO              NaN
Adj Close  AAPL     1.123010e+02
           AMZN     7.498700e+02
           GOOG     7.718200e+02
           MSFT     5.974847e+01
           YHOO              NaN

[30 rows x 1762 columns]

In [70]:
p.swapaxes(1,1)

Attributes        High                                                 Low  \
Symbols           AAPL        AMZN        GOOG       MSFT YHOO        AAPL
Date
2010-01-04   30.642857  136.610001  312.721039  31.100000  NaN   30.340000
2010-01-05   30.798571  135.479996  311.891449  31.100000  NaN   30.464285
2010-01-06   30.747143  134.729996  310.907837  31.080000  NaN   30.107143
2010-01-07   30.285715  132.320007  303.029083  30.700001  NaN   29.864286
2010-01-08   30.285715  133.679993  299.675903  30.879999  NaN   29.865715
2010-01-11   30.428572  132.800003  300.276978  30.760000  NaN   29.778572
2010-01-12   29.967142  129.820007  297.147339  30.400000  NaN   29.488571
2010-01-13   30.132856  129.710007  292.288940  30.520000  NaN   29.157143
2010-01-14   30.065714  130.380005  295.180145  31.100000  NaN   29.860001
2010-01-15   30.228571  129.649994  294.862213  31.240000  NaN   29.410000
2010-01-19   30.741428  128.000000  293.302338  31.240000  NaN   29.605715
2010-01-20   30.792856  129.199997  291.096710  30.940001  NaN   29.928572
2010-01-21   30.472857  128.149994  291.513977  30.719999  NaN   29.601429
2010-01-22   29.642857  127.669998  283.456390  30.200001  NaN   28.165714
2010-01-25   29.242857  122.279999  273.163330  29.660000  NaN   28.598572
2010-01-26   30.530001  122.980003  273.024231  29.850000  NaN   28.940001
2010-01-27   30.082857  123.330002  272.055542  29.820000  NaN   28.504286
2010-01-28   29.357143  127.199997  271.732635  29.870001  NaN   28.385714
2010-01-29   28.885714  131.850006  268.747070  29.920000  NaN   27.178572
2010-02-01   28.000000  124.860001  266.173798  28.480000  NaN   27.328571
2010-02-02   28.045713  118.980003  265.751556  28.500000  NaN   27.625713
2010-02-03   28.600000  119.610001  269.298462  28.790001  NaN   27.774286
2010-02-04   28.338572  120.330002  267.261719  28.500000  NaN   27.367144
2010-02-05   28.000000  117.650002  265.026245  28.280001  NaN   27.264286
2010-02-08   28.268572  121.000000  269.248810  28.080000  NaN   27.714285
2010-02-09   28.214285  119.089996  269.015320  28.340000  NaN   27.821428
2010-02-10   28.085714  118.610001  267.157410  28.240000  NaN   27.751429
2010-02-11   28.535715  120.419998  268.498688  28.400000  NaN   27.722857
2010-02-12   28.805714  119.940002  266.839478  28.059999  NaN   27.928572
2010-02-16   29.098572  120.500000  270.306915  28.370001  NaN   28.788572
...                ...         ...         ...        ...  ...         ...
2016-11-17  110.349998  757.500000  772.700012  60.950001  NaN  108.830002
2016-11-18  110.540001  767.739990  775.000000  61.139999  NaN  109.660004
2016-11-21  111.989998  780.349976  769.700012  60.970001  NaN  110.010002
2016-11-22  112.419998  792.400024  776.960022  61.259998  NaN  111.400002
2016-11-23  111.510002  781.750000  768.283020  61.099998  NaN  110.330002
2016-11-25  111.870003  786.750000  765.000000  60.529999  NaN  110.949997
2016-11-28  112.470001  777.000000  779.530029  61.020000  NaN  111.389999
2016-11-29  112.029999  769.890015  778.500000  61.410000  NaN  110.070000
2016-11-30  112.199997  768.090027  772.989990  61.180000  NaN  110.269997
2016-12-01  110.940002  753.369995  759.849976  60.150002  NaN  109.029999
2016-12-02  110.089996  748.489990  754.000000  59.470001  NaN  108.849998
2016-12-05  110.029999  761.489990  763.900024  60.590000  NaN  108.250000
2016-12-06  110.360001  768.239990  768.830017  60.459999  NaN  109.190002
2016-12-07  111.190002  770.419983  771.359985  61.380001  NaN  109.160004
2016-12-08  112.430000  773.789978  778.179993  61.580002  NaN  110.599998
2016-12-09  114.699997  770.250000  789.429993  61.990002  NaN  112.309998
2016-12-12  115.000000  766.890015  791.250000  62.299999  NaN  112.489998
2016-12-13  115.919998  782.460022  804.380005  63.419998  NaN  113.750000
2016-12-14  116.199997  780.859985  804.000000  63.450001  NaN  114.980003
2016-12-15  116.730003  769.099976  803.000000  63.150002  NaN  115.230003
2016-12-16  116.500000  765.130005  800.856018  62.950001  NaN  115.650002
2016-12-19  117.379997  770.500000  797.659973  63.770000  NaN  115.750000
2016-12-20  117.500000  774.390015  798.650024  63.799999  NaN  116.680000
2016-12-21  117.400002  771.219971  796.676025  63.700001  NaN  116.779999
2016-12-22  116.510002  771.210022  793.320007  64.099998  NaN  115.639999
2016-12-23  116.519997  766.500000  792.739990  63.540001  NaN  115.589996
2016-12-27  117.800003  774.650024  797.859985  64.070000  NaN  116.489998
2016-12-28  118.019997  780.000000  794.229980  63.400002  NaN  116.199997
2016-12-29  117.110001  773.400024  785.929993  63.200001  NaN  116.400002
2016-12-30  117.199997  767.400024  782.780029  62.990002  NaN  115.430000

Attributes                                         ...        Volume  \
Symbols           AMZN        GOOG       MSFT YHOO ...          AAPL
Date                                               ...
2010-01-04  133.139999  310.103088  30.590000  NaN ...   123432400.0
2010-01-05  131.809998  308.761810  30.639999  NaN ...   150476200.0
2010-01-06  131.649994  301.220856  30.520000  NaN ...   138040000.0
2010-01-07  128.800003  294.410156  30.190001  NaN ...   119282800.0
2010-01-08  129.029999  292.651581  30.240000  NaN ...   111902700.0
2010-01-11  129.210007  295.100647  30.120001  NaN ...   115557400.0
2010-01-12  126.550003  292.100159  29.910000  NaN ...   148614900.0
2010-01-13  125.750000  285.095734  30.010000  NaN ...   151473000.0
2010-01-14  126.400002  289.521942  30.260000  NaN ...   108223500.0
2010-01-15  127.059998  287.152344  30.709999  NaN ...   148516900.0
2010-01-19  124.330002  286.283020  30.680000  NaN ...   182501900.0
2010-01-20  125.080002  285.786224  30.309999  NaN ...   153038200.0
2010-01-21  125.000000  284.276062  30.000000  NaN ...   152038600.0
2010-01-22  120.760002  265.701874  28.840000  NaN ...   220441900.0
2010-01-25  118.120003  266.024780  29.100000  NaN ...   266424900.0
2010-01-26  119.059998  266.412231  29.090000  NaN ...   466777500.0
2010-01-27  118.800003  265.925415  29.020000  NaN ...   430642100.0
2010-01-28  122.800003  263.585632  28.889999  NaN ...   293375600.0
2010-01-29  124.139999  261.106750  27.660000  NaN ...   311488100.0
2010-02-01  113.820000  263.436584  27.920000  NaN ...   187469100.0
2010-02-02  114.400002  262.100281  28.139999  NaN ...   174585600.0
2010-02-03  116.559998  262.408295  28.120001  NaN ...   153832000.0
2010-02-04  115.739998  261.081909  27.809999  NaN ...   189413000.0
2010-02-05  114.099998  259.541931  27.570000  NaN ...   212576700.0
2010-02-08  116.559998  264.047638  27.570000  NaN ...   119567700.0
2010-02-09  117.000000  265.806183  27.750000  NaN ...   158221700.0
2010-02-10  116.000000  262.140045  27.840000  NaN ...    92590400.0
2010-02-11  116.500000  263.039185  27.700001  NaN ...   137586400.0
2010-02-12  117.500000  263.535950  27.580000  NaN ...   163867200.0
2010-02-16  117.180000  265.423676  28.020000  NaN ...   135934400.0
...                ...         ...        ...  ... ...           ...
2016-11-17  748.000000  764.229980  59.970001  NaN ...    27632000.0
2016-11-18  757.640015  760.000000  60.299999  NaN ...    28428900.0
2016-11-21  765.109985  760.599976  60.419998  NaN ...    29264600.0
2016-11-22  781.000000  767.000000  60.810001  NaN ...    25965500.0
2016-11-23  773.119995  755.250000  60.250000  NaN ...    27426400.0
2016-11-25  777.900024  760.520020  60.130001  NaN ...    11475900.0
2016-11-28  764.239990  759.799988  60.209999  NaN ...    27194000.0
2016-11-29  761.320007  768.239990  60.520000  NaN ...    28528800.0
2016-11-30  750.250000  754.830017  60.220001  NaN ...    36162300.0
2016-12-01  738.030029  737.025024  58.939999  NaN ...    37086900.0
2016-12-02  736.700012  743.099976  58.799999  NaN ...    26528000.0
2016-12-05  742.000000  752.900024  59.560001  NaN ...    34324500.0
2016-12-06  757.250000  757.340027  59.799999  NaN ...    26195500.0
2016-12-07  755.820007  755.799988  59.799999  NaN ...    29998700.0
2016-12-08  765.190002  767.229980  60.840000  NaN ...    27068300.0
2016-12-09  765.340027  779.020996  61.130001  NaN ...    34402600.0
2016-12-12  757.200012  784.354980  61.720001  NaN ...    26374400.0
2016-12-13  762.000000  793.340027  62.240002  NaN ...    43733800.0
2016-12-14  762.809998  794.010010  62.529999  NaN ...    34031800.0
2016-12-15  760.309998  792.919983  62.299999  NaN ...    46524500.0
2016-12-16  754.000000  790.289978  62.119999  NaN ...    44351100.0
2016-12-19  756.159973  786.270020  62.419998  NaN ...    27779400.0
2016-12-20  767.710022  793.270020  63.029999  NaN ...    21425000.0
2016-12-21  765.700012  787.099976  63.119999  NaN ...    23783200.0
2016-12-22  763.020020  788.580017  63.410000  NaN ...    26085900.0
2016-12-23  757.989990  787.280029  62.799999  NaN ...    14249500.0
2016-12-27  761.200012  787.656982  63.209999  NaN ...    18296900.0
2016-12-28  770.500000  783.200012  62.830002  NaN ...    20905900.0
2016-12-29  760.849976  778.919983  62.730000  NaN ...    15039500.0
2016-12-30  748.280029  770.409973  62.029999  NaN ...    30586300.0

Attributes                                             Adj Close              \
Symbols           AMZN        GOOG         MSFT YHOO        AAPL        AMZN
Date
2010-01-04   7599900.0   3937800.0   38409100.0  NaN   20.473503  133.899994
2010-01-05   8851900.0   6048500.0   49749600.0  NaN   20.508902  134.690002
2010-01-06   7178800.0   8009000.0   58182400.0  NaN   20.182680  132.250000
2010-01-07  11030200.0  12912000.0   50559700.0  NaN   20.145369  130.000000
2010-01-08   9830500.0   9509900.0   51197400.0  NaN   20.279305  133.520004
2010-01-11   8779400.0  14519600.0   68754700.0  NaN   20.100410  130.309998
2010-01-12   9096300.0   9769600.0   65912100.0  NaN   19.871763  127.349998
2010-01-13  10723200.0  13077600.0   51863500.0  NaN   20.152065  129.110001
2010-01-14   9774900.0   8535300.0   63228100.0  NaN   20.035355  127.349998
2010-01-15  15376500.0  10939600.0   79913200.0  NaN   19.700523  127.139999
2010-01-19   8892600.0   8689500.0   46575700.0  NaN   20.572037  127.610001
2010-01-20   9074700.0   6543600.0   54849500.0  NaN   20.255390  125.779999
2010-01-21   9970600.0  12697400.0   73086700.0  NaN   19.905249  126.620003
2010-01-22  11568900.0  13689200.0  102004600.0  NaN   18.917973  121.430000
2010-01-25  12023900.0   8897200.0   63373000.0  NaN   19.426920  120.309998
2010-01-26   9559000.0   8767600.0   66639900.0  NaN   19.701479  119.480003
2010-01-27  14765300.0   7980200.0   63949500.0  NaN   19.887072  122.750000
2010-01-28  27293100.0   6500100.0  117513700.0  NaN   19.065300  126.029999
2010-01-29  29471300.0   8334700.0  193888500.0  NaN   18.373636  125.410004
2010-02-01  37774400.0   4530800.0   85931100.0  NaN   18.629066  118.870003
2010-02-02  23079700.0   8245600.0   54413700.0  NaN   18.737165  118.120003
2010-02-03  12405900.0   6037000.0   61397900.0  NaN   19.059557  119.099998
2010-02-04  12784000.0   6799200.0   77850000.0  NaN   18.372683  115.940002
2010-02-05  11024800.0   6353000.0   80960100.0  NaN   18.698900  117.389999
2010-02-08   9890200.0   5423500.0   52820600.0  NaN   18.570709  116.830002
2010-02-09   9223000.0   5675700.0   59195800.0  NaN   18.768732  118.029999
2010-02-10   6233200.0   5383700.0   48591300.0  NaN   18.666370  117.360001
2010-02-11   8343500.0   4851300.0   65993700.0  NaN   19.005989  120.089996
2010-02-12   8073500.0   4589000.0   81117200.0  NaN   19.169575  119.660004
2010-02-16   8932700.0   7356200.0   51935600.0  NaN   19.458488  117.529999
...                ...         ...          ...  ...         ...         ...
2016-11-17   3690100.0   1304000.0   32132700.0  NaN  106.609329  756.400024
2016-11-18   4373400.0   1547100.0   27686300.0  NaN  106.715996  760.159973
2016-11-21   4614600.0   1330600.0   19652600.0  NaN  108.335266  780.000000
2016-11-22   5311300.0   1593100.0   23206700.0  NaN  108.403137  785.330017
2016-11-23   3522500.0   1477400.0   21847200.0  NaN  107.850449  780.119995
2016-11-25   1837100.0    587400.0    8409600.0  NaN  108.393433  780.369995
2016-11-28   4438800.0   2188200.0   20732600.0  NaN  108.180122  766.770020
2016-11-29   3272300.0   1616600.0   22366700.0  NaN  108.073463  762.520020
2016-11-30   4625900.0   2392900.0   34655400.0  NaN  107.162018  750.570007
2016-12-01   4666000.0   3017900.0   34542100.0  NaN  106.163315  743.650024
2016-12-02   3561300.0   1452500.0   25515700.0  NaN  106.560860  740.340027
2016-12-05   4314700.0   1394200.0   23552700.0  NaN  105.794868  759.359985
2016-12-06   3794700.0   1690700.0   19907000.0  NaN  106.609329  764.719971
2016-12-07   3684900.0   1761000.0   30809000.0  NaN  107.656517  770.419983
2016-12-08   3189600.0   1488100.0   21220800.0  NaN  108.713409  767.330017
2016-12-09   2470900.0   1821900.0   27349400.0  NaN  110.487801  768.659973
2016-12-12   2963900.0   2104100.0   20198100.0  NaN  109.857559  760.119995
2016-12-13   5285300.0   2145200.0   35718900.0  NaN  111.690132  774.340027
2016-12-14   5454800.0   1704200.0   30352700.0  NaN  111.690132  768.820007
2016-12-15   3801900.0   1626500.0   27669900.0  NaN  112.300980  761.000000
2016-12-16   4828700.0   2428300.0   42204700.0  NaN  112.446442  757.770020
2016-12-19   3113200.0   1232100.0   34338200.0  NaN  113.096069  766.000000
2016-12-20   2703600.0    951000.0   26028400.0  NaN  113.396652  771.219971
2016-12-21   2044600.0   1211300.0   17096300.0  NaN  113.503304  770.599976
2016-12-22   2543600.0    972200.0   22176600.0  NaN  112.756714  766.340027
2016-12-23   1976900.0    623400.0   12398000.0  NaN  112.979713  760.590027
2016-12-27   2638700.0    789100.0   11763200.0  NaN  113.697243  771.400024
2016-12-28   3301000.0   1153800.0   14653300.0  NaN  113.212425  772.130005
2016-12-29   3153500.0    742200.0   10181600.0  NaN  113.183334  765.150024
2016-12-30   4139400.0   1770000.0   25579900.0  NaN  112.300980  749.869995

Attributes
Symbols           GOOG       MSFT YHOO
Date
2010-01-04  311.349976  24.720928  NaN
2010-01-05  309.978882  24.728914  NaN
2010-01-06  302.164703  24.577150  NaN
2010-01-07  295.130463  24.321552  NaN
2010-01-08  299.064880  24.489288  NaN
2010-01-11  298.612823  24.177786  NaN
2010-01-12  293.332153  24.018032  NaN
2010-01-13  291.648102  24.241684  NaN
2010-01-14  293.019196  24.728914  NaN
2010-01-15  288.126007  24.649038  NaN
2010-01-19  291.911407  24.840738  NaN
2010-01-20  288.329681  24.433378  NaN
2010-01-21  289.606384  23.970112  NaN
2010-01-22  273.227905  23.131437  NaN
2010-01-25  268.255249  23.418983  NaN
2010-01-26  269.457428  23.562756  NaN
2010-01-27  269.298462  23.698549  NaN
2010-01-28  265.418701  23.291180  NaN
2010-01-29  263.257751  22.508421  NaN
2010-02-01  264.787811  22.692129  NaN
2010-02-02  263.843964  22.732069  NaN
2010-02-03  268.662598  22.867855  NaN
2010-02-04  261.687958  22.236853  NaN
2010-02-05  263.928406  22.380629  NaN
2010-02-08  265.011353  22.141001  NaN
2010-02-09  266.486755  22.372641  NaN
2010-02-10  265.498199  22.356657  NaN
2010-02-11  266.466888  22.460506  NaN
2010-02-12  264.837494  22.308741  NaN
2010-02-16  268.901062  22.750099  NaN
...                ...        ...  ...
2016-11-17  771.229980  58.306213  NaN
2016-11-18  760.539978  58.027370  NaN
2016-11-21  769.200012  58.517738  NaN
2016-11-22  768.270020  58.767731  NaN
2016-11-23  760.989990  58.075451  NaN
2016-11-25  761.679993  58.200436  NaN
2016-11-28  768.239990  58.277363  NaN
2016-11-29  770.840027  58.738884  NaN
2016-11-30  758.039978  57.940830  NaN
2016-12-01  747.919983  56.921623  NaN
2016-12-02  750.500000  56.969700  NaN
2016-12-05  762.520020  57.902378  NaN
2016-12-06  759.109985  57.642761  NaN
2016-12-07  771.190002  59.008118  NaN
2016-12-08  776.419983  58.661968  NaN
2016-12-09  789.289978  59.585018  NaN
2016-12-12  789.270020  59.777321  NaN
2016-12-13  796.099976  60.556149  NaN
2016-12-14  797.070007  60.267696  NaN
2016-12-15  797.849976  60.171543  NaN
2016-12-16  790.799988  59.902313  NaN
2016-12-19  794.200012  61.171520  NaN
2016-12-20  796.419983  61.094597  NaN
2016-12-21  794.559998  61.094597  NaN
2016-12-22  791.260010  61.104214  NaN
2016-12-23  789.909973  60.806145  NaN
2016-12-27  791.549988  60.844601  NaN
2016-12-28  785.049988  60.565762  NaN
2016-12-29  782.789978  60.479229  NaN
2016-12-30  771.820007  59.748470  NaN

[1762 rows x 30 columns]

In [79]:
p.loc["2010-01-12 ", "High"]

Symbols
AAPL     29.967142
AMZN    129.820007
GOOG    297.147339
MSFT     30.400000
YHOO           NaN
Name: 2010-01-12 00:00:00, dtype: float64

In [84]:
p2.swapaxes("items", "minor")

/Users/ninja/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning:
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  """Entry point for launching an IPython kernel.

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1762 (major_axis) x 6 (minor_axis)
Items axis: AAPL to YHOO
Major_axis axis: 2010-01-04 00:00:00 to 2016-12-30 00:00:00
Minor_axis axis: High to Adj Close